import type {
  BookingSource,
  ProductSourceMapping,
  HealthCheckLog,
  SourceHealthCard,
  ResponseTimePoint,
} from "@/types/booking-sources";

// ---- Helper: generate sparkline data ----
function generateSparkline(
  baseMs: number,
  variance: number,
  isOffline: boolean
): ResponseTimePoint[] {
  return Array.from({ length: 10 }, (_, i) => {
    const t = new Date(Date.now() - (9 - i) * 90 * 1000);
    return {
      time: t.toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
      }),
      ms: isOffline && i >= 7
        ? 0
        : Math.max(50, baseMs + Math.floor((Math.random() - 0.5) * variance)),
    };
  });
}

// ---- Booking Sources ----
export const MOCK_BOOKING_SOURCES: BookingSource[] = [
  {
    id: "src-001",
    name: "Viator API",
    code: "viator-api",
    category: "attractions",
    mode: "api",
    endpointUrl: "https://api.viator.com/v2/products",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 9,
    isActive: true,
    ingestionSourceId: "viator",
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    responseTimeMs: 142,
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2026-03-25T08:00:00Z",
  },
  {
    id: "src-002",
    name: "GetYourGuide",
    code: "getyourguide",
    category: "attractions",
    mode: "api",
    endpointUrl: "https://api.getyourguide.com/1/tours",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 8,
    isActive: true,
    ingestionSourceId: "gyg",
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    responseTimeMs: 198,
    createdAt: "2025-06-20T10:00:00Z",
    updatedAt: "2026-03-25T07:30:00Z",
  },
  {
    id: "src-003",
    name: "Booking.com Hotels",
    code: "booking-hotels",
    category: "hotels",
    mode: "api",
    endpointUrl: "https://distribution-xml.booking.com/2.9/json",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 7,
    isActive: true,
    ingestionSourceId: "booking",
    healthStatus: "degraded",
    lastPingTime: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    responseTimeMs: 890,
    createdAt: "2025-05-10T10:00:00Z",
    updatedAt: "2026-03-25T09:00:00Z",
  },
  {
    id: "src-004",
    name: "Hotelbeds",
    code: "hotelbeds",
    category: "hotels",
    mode: "api",
    endpointUrl: "https://api.hotelbeds.com/hotel-api/1.0",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 8,
    isActive: true,
    ingestionSourceId: "hotelbeds",
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    responseTimeMs: 234,
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2026-03-25T06:45:00Z",
  },
  {
    id: "src-005",
    name: "Klook Experiences",
    code: "klook-experiences",
    category: "attractions",
    mode: "api",
    endpointUrl: "https://api.klook.com/v1/activities",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 6,
    isActive: true,
    ingestionSourceId: "klook",
    healthStatus: "offline",
    lastPingTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    responseTimeMs: 0,
    createdAt: "2025-08-12T10:00:00Z",
    updatedAt: "2026-03-25T09:15:00Z",
  },
  {
    id: "src-006",
    name: "Agoda Hotels",
    code: "agoda-hotels",
    category: "hotels",
    mode: "api",
    endpointUrl: "https://api.agoda.com/v2/properties",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 7,
    isActive: true,
    ingestionSourceId: "agoda",
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    responseTimeMs: 312,
    createdAt: "2025-09-05T10:00:00Z",
    updatedAt: "2026-03-25T08:30:00Z",
  },
  {
    id: "src-007",
    name: "DMC Dubai Direct",
    code: "dmc-dubai-direct",
    category: "transfers",
    mode: "manual",
    endpointUrl: null,
    contactEmail: "bookings@dmcdubai.ae",
    contactPhone: "+971-4-555-0100",
    marginPriorityScore: 10,
    isActive: true,
    ingestionSourceId: null,
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    responseTimeMs: 0,
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2026-03-24T14:00:00Z",
  },
  {
    id: "src-008",
    name: "Desert Safari Partners",
    code: "desert-safari-partners",
    category: "attractions",
    mode: "email",
    endpointUrl: null,
    contactEmail: "ops@desertsafari.ae",
    contactPhone: "+971-4-555-0200",
    marginPriorityScore: 9,
    isActive: true,
    ingestionSourceId: null,
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    responseTimeMs: 0,
    createdAt: "2025-11-10T10:00:00Z",
    updatedAt: "2026-03-23T16:00:00Z",
  },
  {
    id: "src-009",
    name: "Restaurant Hub ME",
    code: "restaurant-hub-me",
    category: "restaurants",
    mode: "api",
    endpointUrl: "https://api.restauranthub.me/v1/venues",
    contactEmail: null,
    contactPhone: null,
    marginPriorityScore: 5,
    isActive: true,
    ingestionSourceId: null,
    healthStatus: "online",
    lastPingTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    responseTimeMs: 178,
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2026-03-25T07:00:00Z",
  },
  {
    id: "src-010",
    name: "Transfer Desk",
    code: "transfer-desk",
    category: "transfers",
    mode: "email",
    endpointUrl: null,
    contactEmail: "dispatch@transferdesk.com",
    contactPhone: "+971-4-555-0300",
    marginPriorityScore: 4,
    isActive: false,
    ingestionSourceId: null,
    healthStatus: "offline",
    lastPingTime: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    responseTimeMs: 0,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-20T12:00:00Z",
  },
];

// ---- Product Source Mappings ----
export const MOCK_PRODUCT_MAPPINGS: ProductSourceMapping[] = [
  {
    id: "map-001",
    productName: "Burj Khalifa Observation Deck",
    productCategory: "attractions",
    destination: "Dubai",
    source1Id: "src-001",
    source2Id: "src-002",
    source3Id: "src-005",
    mappingStatus: "complete",
    lastUpdated: "2026-03-24T10:00:00Z",
  },
  {
    id: "map-002",
    productName: "Desert Safari Premium",
    productCategory: "attractions",
    destination: "Dubai",
    source1Id: "src-008",
    source2Id: "src-001",
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-23T14:00:00Z",
  },
  {
    id: "map-003",
    productName: "Atlantis The Palm",
    productCategory: "hotels",
    destination: "Dubai",
    source1Id: "src-003",
    source2Id: "src-004",
    source3Id: "src-006",
    mappingStatus: "complete",
    lastUpdated: "2026-03-25T08:00:00Z",
  },
  {
    id: "map-004",
    productName: "Airport Transfer DXB",
    productCategory: "transfers",
    destination: "Dubai",
    source1Id: "src-007",
    source2Id: null,
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-22T09:00:00Z",
  },
  {
    id: "map-005",
    productName: "La Petite Maison",
    productCategory: "restaurants",
    destination: "Dubai",
    source1Id: "src-009",
    source2Id: null,
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-21T11:00:00Z",
  },
  {
    id: "map-006",
    productName: "Abu Dhabi City Tour",
    productCategory: "attractions",
    destination: "Abu Dhabi",
    source1Id: "src-001",
    source2Id: "src-002",
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-24T15:00:00Z",
  },
  {
    id: "map-007",
    productName: "Yas Viceroy Hotel",
    productCategory: "hotels",
    destination: "Abu Dhabi",
    source1Id: "src-004",
    source2Id: "src-006",
    source3Id: "src-003",
    mappingStatus: "complete",
    lastUpdated: "2026-03-25T07:00:00Z",
  },
  {
    id: "map-008",
    productName: "Istanbul Old Town Walking Tour",
    productCategory: "attractions",
    destination: "Istanbul",
    source1Id: "src-002",
    source2Id: null,
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-20T16:00:00Z",
  },
  {
    id: "map-009",
    productName: "Four Seasons Bosphorus",
    productCategory: "hotels",
    destination: "Istanbul",
    source1Id: "src-003",
    source2Id: "src-004",
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-22T12:00:00Z",
  },
  {
    id: "map-010",
    productName: "Maldives Seaplane Transfer",
    productCategory: "transfers",
    destination: "Maldives",
    source1Id: null,
    source2Id: null,
    source3Id: null,
    mappingStatus: "unmapped",
    lastUpdated: "2026-03-18T10:00:00Z",
  },
  {
    id: "map-011",
    productName: "Soneva Fushi Resort",
    productCategory: "hotels",
    destination: "Maldives",
    source1Id: "src-004",
    source2Id: null,
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-19T08:00:00Z",
  },
  {
    id: "map-012",
    productName: "Tbilisi Food Tour",
    productCategory: "restaurants",
    destination: "Georgia",
    source1Id: null,
    source2Id: null,
    source3Id: null,
    mappingStatus: "unmapped",
    lastUpdated: "2026-03-17T14:00:00Z",
  },
  {
    id: "map-013",
    productName: "Rooms Hotel Tbilisi",
    productCategory: "hotels",
    destination: "Georgia",
    source1Id: "src-003",
    source2Id: null,
    source3Id: null,
    mappingStatus: "partial",
    lastUpdated: "2026-03-20T10:00:00Z",
  },
  {
    id: "map-014",
    productName: "Dubai Frame Tickets",
    productCategory: "attractions",
    destination: "Dubai",
    source1Id: "src-005",
    source2Id: "src-001",
    source3Id: "src-002",
    mappingStatus: "complete",
    lastUpdated: "2026-03-25T06:00:00Z",
  },
  {
    id: "map-015",
    productName: "Oman Wahiba Sands Excursion",
    productCategory: "attractions",
    destination: "Oman",
    source1Id: null,
    source2Id: null,
    source3Id: null,
    mappingStatus: "unmapped",
    lastUpdated: "2026-03-16T09:00:00Z",
  },
];

// ---- Health Check Logs ----
export const MOCK_HEALTH_LOGS: HealthCheckLog[] = [
  { id: "hc-001", sourceId: "src-001", sourceName: "Viator API", status: "online", responseTimeMs: 142, errorMessage: null, checkedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
  { id: "hc-002", sourceId: "src-002", sourceName: "GetYourGuide", status: "online", responseTimeMs: 198, errorMessage: null, checkedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
  { id: "hc-003", sourceId: "src-003", sourceName: "Booking.com Hotels", status: "degraded", responseTimeMs: 890, errorMessage: "Response time exceeded 500ms threshold", checkedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString() },
  { id: "hc-004", sourceId: "src-004", sourceName: "Hotelbeds", status: "online", responseTimeMs: 234, errorMessage: null, checkedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
  { id: "hc-005", sourceId: "src-005", sourceName: "Klook Experiences", status: "offline", responseTimeMs: 0, errorMessage: "Connection refused — host unreachable", checkedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
  { id: "hc-006", sourceId: "src-006", sourceName: "Agoda Hotels", status: "online", responseTimeMs: 312, errorMessage: null, checkedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
  { id: "hc-007", sourceId: "src-009", sourceName: "Restaurant Hub ME", status: "online", responseTimeMs: 178, errorMessage: null, checkedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
  { id: "hc-008", sourceId: "src-001", sourceName: "Viator API", status: "online", responseTimeMs: 156, errorMessage: null, checkedAt: new Date(Date.now() - 17 * 60 * 1000).toISOString() },
  { id: "hc-009", sourceId: "src-003", sourceName: "Booking.com Hotels", status: "degraded", responseTimeMs: 920, errorMessage: "Response time exceeded 500ms threshold", checkedAt: new Date(Date.now() - 16 * 60 * 1000).toISOString() },
  { id: "hc-010", sourceId: "src-005", sourceName: "Klook Experiences", status: "offline", responseTimeMs: 0, errorMessage: "Connection refused — host unreachable", checkedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: "hc-011", sourceId: "src-005", sourceName: "Klook Experiences", status: "degraded", responseTimeMs: 1200, errorMessage: "Response time exceeded 1000ms threshold", checkedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString() },
  { id: "hc-012", sourceId: "src-002", sourceName: "GetYourGuide", status: "online", responseTimeMs: 210, errorMessage: null, checkedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString() },
  { id: "hc-013", sourceId: "src-004", sourceName: "Hotelbeds", status: "online", responseTimeMs: 245, errorMessage: null, checkedAt: new Date(Date.now() - 19 * 60 * 1000).toISOString() },
  { id: "hc-014", sourceId: "src-006", sourceName: "Agoda Hotels", status: "online", responseTimeMs: 298, errorMessage: null, checkedAt: new Date(Date.now() - 17 * 60 * 1000).toISOString() },
  { id: "hc-015", sourceId: "src-003", sourceName: "Booking.com Hotels", status: "online", responseTimeMs: 456, errorMessage: null, checkedAt: new Date(Date.now() - 31 * 60 * 1000).toISOString() },
  { id: "hc-016", sourceId: "src-001", sourceName: "Viator API", status: "online", responseTimeMs: 138, errorMessage: null, checkedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString() },
  { id: "hc-017", sourceId: "src-009", sourceName: "Restaurant Hub ME", status: "online", responseTimeMs: 190, errorMessage: null, checkedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
  { id: "hc-018", sourceId: "src-005", sourceName: "Klook Experiences", status: "online", responseTimeMs: 340, errorMessage: null, checkedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString() },
  { id: "hc-019", sourceId: "src-003", sourceName: "Booking.com Hotels", status: "degraded", responseTimeMs: 780, errorMessage: "Response time exceeded 500ms threshold", checkedAt: new Date(Date.now() - 46 * 60 * 1000).toISOString() },
  { id: "hc-020", sourceId: "src-002", sourceName: "GetYourGuide", status: "online", responseTimeMs: 185, errorMessage: null, checkedAt: new Date(Date.now() - 33 * 60 * 1000).toISOString() },
];

// ---- Source Health Cards ----
export const MOCK_SOURCE_HEALTH_CARDS: SourceHealthCard[] = [
  {
    sourceId: "src-001",
    sourceName: "Viator API",
    category: "attractions",
    status: "online",
    responseTimeMs: 142,
    lastChecked: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    errorMessage: null,
    sparkline: generateSparkline(150, 40, false),
    affectedProductCount: 0,
  },
  {
    sourceId: "src-002",
    sourceName: "GetYourGuide",
    category: "attractions",
    status: "online",
    responseTimeMs: 198,
    lastChecked: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    errorMessage: null,
    sparkline: generateSparkline(200, 50, false),
    affectedProductCount: 0,
  },
  {
    sourceId: "src-003",
    sourceName: "Booking.com Hotels",
    category: "hotels",
    status: "degraded",
    responseTimeMs: 890,
    lastChecked: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    errorMessage: "Response time exceeded 500ms threshold",
    sparkline: generateSparkline(700, 300, false),
    affectedProductCount: 0,
  },
  {
    sourceId: "src-004",
    sourceName: "Hotelbeds",
    category: "hotels",
    status: "online",
    responseTimeMs: 234,
    lastChecked: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    errorMessage: null,
    sparkline: generateSparkline(240, 60, false),
    affectedProductCount: 0,
  },
  {
    sourceId: "src-005",
    sourceName: "Klook Experiences",
    category: "attractions",
    status: "offline",
    responseTimeMs: 0,
    lastChecked: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    errorMessage: "Connection refused — host unreachable",
    sparkline: generateSparkline(300, 80, true),
    affectedProductCount: 2,
  },
  {
    sourceId: "src-006",
    sourceName: "Agoda Hotels",
    category: "hotels",
    status: "online",
    responseTimeMs: 312,
    lastChecked: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    errorMessage: null,
    sparkline: generateSparkline(310, 70, false),
    affectedProductCount: 0,
  },
  {
    sourceId: "src-009",
    sourceName: "Restaurant Hub ME",
    category: "restaurants",
    status: "online",
    responseTimeMs: 178,
    lastChecked: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    errorMessage: null,
    sparkline: generateSparkline(180, 40, false),
    affectedProductCount: 0,
  },
];

// ---- Ingestion source options (for FK dropdown) ----
export const MOCK_INGESTION_SOURCES = [
  { id: "viator", name: "Viator" },
  { id: "gyg", name: "GetYourGuide" },
  { id: "booking", name: "Booking.com" },
  { id: "hotelbeds", name: "Hotelbeds" },
  { id: "klook", name: "Klook" },
  { id: "agoda", name: "Agoda" },
];

// ---- All unique destinations from mappings ----
export const MOCK_DESTINATIONS = [
  "Dubai",
  "Abu Dhabi",
  "Istanbul",
  "Maldives",
  "Georgia",
  "Oman",
];
