import type {
  ClassificationRecord,
  ClassificationQueueStats,
} from "@/types/classification";

export const MOCK_CLASSIFICATION_STATS: ClassificationQueueStats = {
  pending: 12,
  assignedToMe: 4,
  inReview: 3,
  completedToday: 27,
};

export const MOCK_CLASSIFICATION_RECORDS: ClassificationRecord[] = [
  {
    id: "cr-001",
    normalizedPayload: {
      id: "np-001",
      name: "Atlantis The Palm",
      description:
        "Iconic 5-star resort situated on the crescent of the Palm Jumeirah, offering luxury rooms, an aquapark, aquarium, and multiple dining options. Features 1,548 rooms with ocean views and direct beach access.",
      source_url: "https://booking.com/hotel/ae/atlantis-the-palm",
      location: {
        address: "Crescent Rd, The Palm Jumeirah",
        city: "Dubai",
        country: "United Arab Emirates",
        latitude: 25.1304,
        longitude: 55.1172,
      },
      pricing: { currency: "AED", amount: 1850, per: "night" },
      images: [
        "https://images.example.com/atlantis-1.jpg",
        "https://images.example.com/atlantis-2.jpg",
      ],
      raw_category: "resort_hotel",
      source_metadata: { stars: 5, review_score: 8.7, review_count: 12453 },
    },
    source: "Booking.com",
    destination: "Dubai",
    predictedCategory: "hotels",
    confidenceScore: 0.94,
    classifierRationale:
      "Strong hotel indicators: 'resort', 'rooms', 'check-in'. Source is a hotel booking platform. Pricing is per-night. Location matches a known hotel property on Palm Jumeirah.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T08:12:00Z",
    updatedAt: "2026-03-25T08:12:00Z",
  },
  {
    id: "cr-002",
    normalizedPayload: {
      id: "np-002",
      name: "Desert Safari with BBQ Dinner",
      description:
        "Experience the Arabian desert with dune bashing, camel riding, sandboarding, and a traditional BBQ dinner under the stars. Includes hotel pickup and drop-off from Dubai hotels.",
      source_url: "https://viator.com/tours/dubai/desert-safari",
      location: {
        address: "Dubai Desert Conservation Reserve",
        city: "Dubai",
        country: "United Arab Emirates",
        latitude: 24.9872,
        longitude: 55.6497,
      },
      pricing: { currency: "AED", amount: 189, per: "person" },
      images: ["https://images.example.com/safari-1.jpg"],
      raw_category: "outdoor_activity",
      source_metadata: { duration_hours: 6, rating: 4.6, reviews: 8934 },
    },
    source: "Viator API",
    destination: "Dubai",
    predictedCategory: "attractions",
    confidenceScore: 0.91,
    classifierRationale:
      "Activity-based listing with 'tours', 'experience', 'camel riding'. Priced per-person (not per-night). Viator is a tours/activities platform. Duration indicates a day activity.",
    assignedTo: "Sarah K.",
    status: "in_review",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T07:45:00Z",
    updatedAt: "2026-03-25T09:30:00Z",
  },
  {
    id: "cr-003",
    normalizedPayload: {
      id: "np-003",
      name: "Dubai Airport Private Transfer",
      description:
        "Private car transfer from Dubai International Airport (DXB) to any hotel in Dubai. Meet & greet service with name board. Available 24/7 with flight tracking.",
      source_url: "https://getyourguide.com/dubai/airport-transfer",
      location: {
        address: "Dubai International Airport, Terminal 3",
        city: "Dubai",
        country: "United Arab Emirates",
        latitude: 25.2528,
        longitude: 55.3644,
      },
      pricing: { currency: "AED", amount: 145, per: "vehicle" },
      images: ["https://images.example.com/transfer-1.jpg"],
      raw_category: "ground_transport",
      source_metadata: { vehicle_type: "sedan", max_passengers: 3, luggage_pieces: 2 },
    },
    source: "GetYourGuide",
    destination: "Dubai",
    predictedCategory: "transfers",
    confidenceScore: 0.87,
    classifierRationale:
      "Clear transfer indicators: 'airport', 'private car transfer', 'meet & greet'. Vehicle-based pricing. Source metadata includes vehicle specs. Airport pickup/dropoff service.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T06:20:00Z",
    updatedAt: "2026-03-25T06:20:00Z",
  },
  {
    id: "cr-004",
    normalizedPayload: {
      id: "np-004",
      name: "Pierchic Restaurant",
      description:
        "Award-winning seafood restaurant located at the end of a pier at Al Qasr hotel, offering panoramic views of the Arabian Gulf. Mediterranean-inspired seafood with an extensive wine list.",
      source_url: "https://tripadvisor.com/Restaurant_Review-pierchic",
      location: {
        address: "Al Qasr Hotel, Madinat Jumeirah",
        city: "Dubai",
        country: "United Arab Emirates",
        latitude: 25.1345,
        longitude: 55.1856,
      },
      pricing: { currency: "AED", amount: 450, per: "person_avg" },
      images: [
        "https://images.example.com/pierchic-1.jpg",
        "https://images.example.com/pierchic-2.jpg",
      ],
      raw_category: "fine_dining",
      source_metadata: { cuisine: "Seafood", price_level: 4, rating: 4.5, review_count: 2341 },
    },
    source: "TripAdvisor",
    destination: "Dubai",
    predictedCategory: "restaurants",
    confidenceScore: 0.96,
    classifierRationale:
      "Explicit dining venue: 'restaurant', 'seafood', 'wine list'. Source is TripAdvisor restaurant section. Has cuisine type and price level. Category 'fine_dining' is restaurant-specific.",
    assignedTo: "Ahmed R.",
    status: "approved",
    finalCategory: "restaurants",
    reviewNotes: "Confirmed as fine dining restaurant. Category correct.",
    reviewedBy: "Ahmed R.",
    createdAt: "2026-03-24T14:00:00Z",
    updatedAt: "2026-03-25T08:45:00Z",
  },
  {
    id: "cr-005",
    normalizedPayload: {
      id: "np-005",
      name: "Louvre Abu Dhabi Skip-the-Line Tickets",
      description:
        "Visit the stunning Louvre Abu Dhabi museum with skip-the-line access. Explore 12 galleries showcasing art from ancient civilizations to contemporary works. Audio guide included.",
      source_url: "https://klook.com/activity/louvre-abu-dhabi",
      location: {
        address: "Saadiyat Island Cultural District",
        city: "Abu Dhabi",
        country: "United Arab Emirates",
        latitude: 24.5338,
        longitude: 54.3983,
      },
      pricing: { currency: "AED", amount: 63, per: "person" },
      images: ["https://images.example.com/louvre-1.jpg"],
      raw_category: "museum_ticket",
      source_metadata: { duration_hours: 3, rating: 4.8, instant_confirmation: true },
    },
    source: "Klook",
    destination: "Abu Dhabi",
    predictedCategory: "attractions",
    confidenceScore: 0.89,
    classifierRationale:
      "Museum/cultural attraction: 'museum', 'galleries', 'art'. Ticket-based entry with per-person pricing. Source is activity booking platform. Duration suggests a visit activity.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T05:30:00Z",
    updatedAt: "2026-03-25T05:30:00Z",
  },
  {
    id: "cr-006",
    normalizedPayload: {
      id: "np-006",
      name: "Thai Cooking Class & Market Tour",
      description:
        "Learn to cook authentic Thai dishes in a hands-on class led by a local chef. Starts with a guided tour of a local market to pick fresh ingredients. Cook 5 dishes including pad thai and green curry.",
      source_url: "https://viator.com/tours/bangkok/cooking-class",
      location: {
        address: "123 Sukhumvit Soi 38",
        city: "Bangkok",
        country: "Thailand",
        latitude: 13.7214,
        longitude: 100.5672,
      },
      pricing: { currency: "THB", amount: 1500, per: "person" },
      images: ["https://images.example.com/cooking-1.jpg"],
      raw_category: "food_experience",
      source_metadata: { duration_hours: 4, group_size_max: 10, rating: 4.9 },
    },
    source: "Viator API",
    destination: "Bangkok",
    predictedCategory: "attractions",
    confidenceScore: 0.52,
    classifierRationale:
      "Mixed signals: 'cooking class' suggests activity (attraction), but 'market tour' and 'food' could indicate restaurant category. Listed on activity platform but involves food/cooking. Classified as attraction due to tour/class nature, though borderline.",
    assignedTo: "Priya M.",
    status: "in_review",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T04:15:00Z",
    updatedAt: "2026-03-25T07:00:00Z",
  },
  {
    id: "cr-007",
    normalizedPayload: {
      id: "np-007",
      name: "Rixos Premium Saadiyat Island",
      description:
        "All-inclusive luxury beach resort on Saadiyat Island with private beach, 6 restaurants, spa, kids club, and direct access to the Saadiyat Beach golf course. Features 378 rooms and suites.",
      source_url: "https://agoda.com/rixos-premium-saadiyat",
      location: {
        address: "Saadiyat Island",
        city: "Abu Dhabi",
        country: "United Arab Emirates",
        latitude: 24.5456,
        longitude: 54.4321,
      },
      pricing: { currency: "AED", amount: 2200, per: "night" },
      images: [
        "https://images.example.com/rixos-1.jpg",
        "https://images.example.com/rixos-2.jpg",
        "https://images.example.com/rixos-3.jpg",
      ],
      raw_category: "beach_resort",
      source_metadata: { stars: 5, review_score: 9.1, all_inclusive: true },
    },
    source: "Agoda",
    destination: "Abu Dhabi",
    predictedCategory: "hotels",
    confidenceScore: 0.97,
    classifierRationale:
      "Very strong hotel signals: 'resort', 'rooms and suites', 'all-inclusive'. Per-night pricing. Source is hotel booking platform. High star rating. Clear accommodation listing.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T03:00:00Z",
    updatedAt: "2026-03-25T03:00:00Z",
  },
  {
    id: "cr-008",
    normalizedPayload: {
      id: "np-008",
      name: "Bosphorus Dinner Cruise",
      description:
        "Evening cruise along the Bosphorus strait with a 4-course Turkish dinner, live music, and belly dancing show. See illuminated landmarks including Dolmabahce Palace and the Maiden's Tower.",
      source_url: "https://getyourguide.com/istanbul/bosphorus-cruise",
      location: {
        address: "Kabatas Cruise Port",
        city: "Istanbul",
        country: "Turkey",
        latitude: 41.0332,
        longitude: 28.9835,
      },
      pricing: { currency: "TRY", amount: 850, per: "person" },
      images: ["https://images.example.com/bosphorus-1.jpg"],
      raw_category: "evening_cruise",
      source_metadata: { duration_hours: 3, meals_included: true, rating: 4.3 },
    },
    source: "GetYourGuide",
    destination: "Istanbul",
    predictedCategory: "restaurants",
    confidenceScore: 0.38,
    classifierRationale:
      "Dinner component is prominent: '4-course Turkish dinner', 'dining'. However, this is primarily a cruise/tour experience. Classified as restaurant due to dinner emphasis, but could be attraction. Low confidence — ambiguous between dining and sightseeing activity.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T02:45:00Z",
    updatedAt: "2026-03-25T02:45:00Z",
  },
  {
    id: "cr-009",
    normalizedPayload: {
      id: "np-009",
      name: "Abu Dhabi to Dubai Shared Shuttle",
      description:
        "Comfortable shared shuttle service between Abu Dhabi city center and Dubai Mall. Air-conditioned minivan with WiFi. Departures every 2 hours from 7am to 9pm daily.",
      source_url: "https://bookaway.com/routes/abudhabi-dubai",
      location: {
        address: "Abu Dhabi Bus Station, Hamdan St",
        city: "Abu Dhabi",
        country: "United Arab Emirates",
        latitude: 24.4871,
        longitude: 54.3654,
      },
      pricing: { currency: "AED", amount: 55, per: "person" },
      images: ["https://images.example.com/shuttle-1.jpg"],
      raw_category: "intercity_bus",
      source_metadata: { vehicle_type: "minivan", duration_hours: 1.5, frequency: "every_2h" },
    },
    source: "Bookaway",
    destination: "Abu Dhabi",
    predictedCategory: "transfers",
    confidenceScore: 0.82,
    classifierRationale:
      "Inter-city transport service: 'shuttle', 'bus station'. Vehicle-based with scheduled departures. Route-based transport between two cities. Clear transfer/transport category.",
    assignedTo: "Sarah K.",
    status: "approved",
    finalCategory: "transfers",
    reviewNotes: "Shared shuttle is a transfer product. Approved as-is.",
    reviewedBy: "Sarah K.",
    createdAt: "2026-03-24T18:00:00Z",
    updatedAt: "2026-03-25T06:15:00Z",
  },
  {
    id: "cr-010",
    normalizedPayload: {
      id: "np-010",
      name: "Grand Bazaar Guided Walking Tour",
      description:
        "Explore Istanbul's legendary Grand Bazaar with a local guide. Visit 3,000+ shops across 61 covered streets. Learn about the 500-year history, try Turkish tea, and discover hidden gems.",
      source_url: "https://viator.com/tours/istanbul/grand-bazaar",
      location: {
        address: "Beyazit Mahallesi, Grand Bazaar",
        city: "Istanbul",
        country: "Turkey",
        latitude: 41.0106,
        longitude: 28.968,
      },
      pricing: { currency: "TRY", amount: 450, per: "person" },
      images: ["https://images.example.com/bazaar-1.jpg"],
      raw_category: "walking_tour",
      source_metadata: { duration_hours: 2.5, group_size_max: 15, rating: 4.7 },
    },
    source: "Viator API",
    destination: "Istanbul",
    predictedCategory: "attractions",
    confidenceScore: 0.85,
    classifierRationale:
      "Guided walking tour: 'tour', 'guide', 'explore'. Activity-based per-person pricing. Source is activity platform. Duration and group size indicate organized tour activity.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T01:30:00Z",
    updatedAt: "2026-03-25T01:30:00Z",
  },
  {
    id: "cr-011",
    normalizedPayload: {
      id: "np-011",
      name: "Chatuchak Weekend Market Food Tour",
      description:
        "A guided food tour through Bangkok's famous Chatuchak Weekend Market. Sample 10+ Thai street food dishes including mango sticky rice, boat noodles, and coconut ice cream.",
      source_url: "https://klook.com/activity/bangkok/chatuchak-food-tour",
      location: {
        address: "Chatuchak Weekend Market",
        city: "Bangkok",
        country: "Thailand",
        latitude: 13.7999,
        longitude: 100.5504,
      },
      pricing: { currency: "THB", amount: 1200, per: "person" },
      images: ["https://images.example.com/chatuchak-1.jpg"],
      raw_category: "food_tour",
      source_metadata: { duration_hours: 3, tastings: 10, rating: 4.8 },
    },
    source: "Klook",
    destination: "Bangkok",
    predictedCategory: "restaurants",
    confidenceScore: 0.45,
    classifierRationale:
      "Significant food focus: 'food tour', 'street food dishes', 'sample'. But this is a guided tour activity, not a sit-down restaurant. Classified as restaurant due to food emphasis but this is borderline — could be attraction.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-25T00:15:00Z",
    updatedAt: "2026-03-25T00:15:00Z",
  },
  {
    id: "cr-012",
    normalizedPayload: {
      id: "np-012",
      name: "Shangri-La Bosphorus Hotel",
      description:
        "Luxury waterfront hotel on the European side of Istanbul with views of the Bosphorus. Features an indoor pool, Shang Palace Chinese restaurant, and the CHI Spa. 186 rooms and suites.",
      source_url: "https://booking.com/hotel/tr/shangri-la-bosphorus",
      location: {
        address: "Sinanpasa Mah, Hayrettin Iskelesi Sok No. 1",
        city: "Istanbul",
        country: "Turkey",
        latitude: 41.0378,
        longitude: 29.0065,
      },
      pricing: { currency: "TRY", amount: 8500, per: "night" },
      images: [
        "https://images.example.com/shangrila-1.jpg",
        "https://images.example.com/shangrila-2.jpg",
      ],
      raw_category: "luxury_hotel",
      source_metadata: { stars: 5, review_score: 9.3, room_count: 186 },
    },
    source: "Booking.com",
    destination: "Istanbul",
    predictedCategory: "hotels",
    confidenceScore: 0.98,
    classifierRationale:
      "Definitive hotel listing: 'hotel', 'rooms and suites', 'indoor pool', 'spa'. Per-night pricing on hotel booking platform. 5-star property with room count. No ambiguity.",
    assignedTo: "Ahmed R.",
    status: "approved",
    finalCategory: "hotels",
    reviewNotes: "Clear hotel classification. Auto-approved due to high confidence.",
    reviewedBy: "Ahmed R.",
    createdAt: "2026-03-24T12:00:00Z",
    updatedAt: "2026-03-24T12:05:00Z",
  },
  {
    id: "cr-013",
    normalizedPayload: {
      id: "np-013",
      name: "Muay Thai Boxing Experience",
      description:
        "Watch a live Muay Thai boxing match at Rajadamnern Stadium followed by optional training session with professional fighters. VIP ringside seats with complimentary drinks.",
      source_url: "https://getyourguide.com/bangkok/muay-thai",
      location: {
        address: "Rajadamnern Stadium, Ratchadamnoen Nok Rd",
        city: "Bangkok",
        country: "Thailand",
        latitude: 13.7636,
        longitude: 100.5069,
      },
      pricing: { currency: "THB", amount: 2500, per: "person" },
      images: ["https://images.example.com/muaythai-1.jpg"],
      raw_category: "sporting_event",
      source_metadata: { duration_hours: 3, vip_available: true, rating: 4.4 },
    },
    source: "GetYourGuide",
    destination: "Bangkok",
    predictedCategory: "attractions",
    confidenceScore: 0.78,
    classifierRationale:
      "Entertainment/sporting event: 'experience', 'boxing match', 'stadium'. Per-person pricing for event tickets. Activity/entertainment platform listing. Classified as attraction.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-24T22:30:00Z",
    updatedAt: "2026-03-24T22:30:00Z",
  },
  {
    id: "cr-014",
    normalizedPayload: {
      id: "np-014",
      name: "Istanbul Airport IST to City Center",
      description:
        "Private sedan transfer from Istanbul Airport (IST) to your hotel in the city center. Professional English-speaking driver, flight monitoring, and 60 minutes of free waiting time.",
      source_url: "https://intui.travel/istanbul-airport-transfer",
      location: {
        address: "Istanbul Airport (IST), Arnavutkoy",
        city: "Istanbul",
        country: "Turkey",
        latitude: 41.2608,
        longitude: 28.7419,
      },
      pricing: { currency: "TRY", amount: 950, per: "vehicle" },
      images: ["https://images.example.com/ist-transfer-1.jpg"],
      raw_category: "airport_transfer",
      source_metadata: { vehicle_type: "sedan", max_passengers: 3, free_wait_min: 60 },
    },
    source: "Intui Travel",
    destination: "Istanbul",
    predictedCategory: "transfers",
    confidenceScore: 0.93,
    classifierRationale:
      "Airport transfer service: 'airport', 'transfer', 'private sedan'. Vehicle-based pricing. Flight monitoring and waiting time are transfer-specific features. Clear transport listing.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-24T20:00:00Z",
    updatedAt: "2026-03-24T20:00:00Z",
  },
  {
    id: "cr-015",
    normalizedPayload: {
      id: "np-015",
      name: "Mikla Restaurant",
      description:
        "Rooftop restaurant atop The Marmara Pera hotel with panoramic Golden Horn views. Modern Turkish-Scandinavian fusion cuisine by Chef Mehmet Gurs. Reservations required.",
      source_url: "https://tripadvisor.com/Restaurant_Review-mikla",
      location: {
        address: "The Marmara Pera, Mesrutiyet Cad No. 15",
        city: "Istanbul",
        country: "Turkey",
        latitude: 41.0301,
        longitude: 28.975,
      },
      pricing: { currency: "TRY", amount: 1200, per: "person_avg" },
      images: ["https://images.example.com/mikla-1.jpg"],
      raw_category: "fine_dining",
      source_metadata: { cuisine: "Turkish-Scandinavian", price_level: 4, rating: 4.6 },
    },
    source: "TripAdvisor",
    destination: "Istanbul",
    predictedCategory: "restaurants",
    confidenceScore: 0.95,
    classifierRationale:
      "Clear restaurant listing: 'restaurant', 'cuisine', 'chef', 'reservations'. TripAdvisor restaurant section. Has cuisine type and price level. Fine dining establishment.",
    assignedTo: "Priya M.",
    status: "approved",
    finalCategory: "restaurants",
    reviewNotes: "Fine dining restaurant confirmed.",
    reviewedBy: "Priya M.",
    createdAt: "2026-03-24T16:00:00Z",
    updatedAt: "2026-03-24T18:30:00Z",
  },
  {
    id: "cr-016",
    normalizedPayload: {
      id: "np-016",
      name: "Spa & Wellness Day at Jumeirah Al Naseem",
      description:
        "Full-day spa package at Talise Spa including hammam, deep tissue massage, facial, and pool access. Lunch at Rockfish restaurant included. Located within the Madinat Jumeirah resort.",
      source_url: "https://viator.com/tours/dubai/spa-day-jumeirah",
      location: {
        address: "Jumeirah Al Naseem, Madinat Jumeirah",
        city: "Dubai",
        country: "United Arab Emirates",
        latitude: 25.1331,
        longitude: 55.1878,
      },
      pricing: { currency: "AED", amount: 890, per: "person" },
      images: ["https://images.example.com/spa-1.jpg"],
      raw_category: "spa_wellness",
      source_metadata: { duration_hours: 6, includes_lunch: true, rating: 4.7 },
    },
    source: "Viator API",
    destination: "Dubai",
    predictedCategory: "hotels",
    confidenceScore: 0.31,
    classifierRationale:
      "Located within a hotel resort complex: 'Jumeirah Al Naseem', 'resort'. But this is a day-use spa package, not accommodation. The 'hotel' classification is likely incorrect — this is more of an attraction/experience. Low confidence due to mixed signals.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-24T15:00:00Z",
    updatedAt: "2026-03-24T15:00:00Z",
  },
  {
    id: "cr-017",
    normalizedPayload: {
      id: "np-017",
      name: "Wat Pho Temple & Reclining Buddha Tour",
      description:
        "Guided tour of Wat Pho, home to the famous 46-meter Reclining Buddha. Learn about Thai Buddhist traditions, explore the temple complex, and optionally receive a traditional Thai massage at the temple's school.",
      source_url: "https://klook.com/activity/bangkok/wat-pho",
      location: {
        address: "2 Sanam Chai Rd, Phra Nakhon",
        city: "Bangkok",
        country: "Thailand",
        latitude: 13.7468,
        longitude: 100.4927,
      },
      pricing: { currency: "THB", amount: 700, per: "person" },
      images: ["https://images.example.com/watpho-1.jpg"],
      raw_category: "temple_tour",
      source_metadata: { duration_hours: 2, rating: 4.7, skip_line: true },
    },
    source: "Klook",
    destination: "Bangkok",
    predictedCategory: "attractions",
    confidenceScore: 0.92,
    classifierRationale:
      "Temple/cultural attraction: 'temple', 'tour', 'guided'. Cultural/religious site visit. Per-person pricing on activity platform. Duration indicates organized tour. Clear attraction.",
    assignedTo: null,
    status: "pending",
    finalCategory: null,
    reviewNotes: null,
    reviewedBy: null,
    createdAt: "2026-03-24T11:00:00Z",
    updatedAt: "2026-03-24T11:00:00Z",
  },
  {
    id: "cr-018",
    normalizedPayload: {
      id: "np-018",
      name: "Emirates Palace Stay & Dine",
      description:
        "Luxury package at Emirates Palace featuring one night in a Coral Room, breakfast buffet, and a 3-course dinner at Hakkasan restaurant. Includes access to the private beach and pool.",
      source_url: "https://booking.com/hotel/ae/emirates-palace",
      location: {
        address: "West Corniche Rd",
        city: "Abu Dhabi",
        country: "United Arab Emirates",
        latitude: 24.4615,
        longitude: 54.3175,
      },
      pricing: { currency: "AED", amount: 3200, per: "night" },
      images: [
        "https://images.example.com/epalace-1.jpg",
        "https://images.example.com/epalace-2.jpg",
      ],
      raw_category: "hotel_package",
      source_metadata: { stars: 5, review_score: 9.0, includes_dining: true },
    },
    source: "Booking.com",
    destination: "Abu Dhabi",
    predictedCategory: "hotels",
    confidenceScore: 0.65,
    classifierRationale:
      "Hotel accommodation package with dining component: 'stay', 'room', 'breakfast'. Per-night pricing on hotel platform. However, the 'dine' component and restaurant inclusion add some ambiguity. Classified as hotel since accommodation is primary, but confidence is moderate.",
    assignedTo: "Sarah K.",
    status: "escalated",
    finalCategory: null,
    reviewNotes:
      "This is a hotel+dining package. Could be split into hotel and restaurant entries. Escalating for team discussion on how to handle combo packages.",
    reviewedBy: "Sarah K.",
    createdAt: "2026-03-24T09:00:00Z",
    updatedAt: "2026-03-25T10:00:00Z",
  },
];
