import type {
  AppUser,
  RoleHistoryEntry,
  UserActivityEntry,
} from "@/types/users";

// ---- Users ----
export const MOCK_USERS: AppUser[] = [
  {
    id: "usr-001",
    fullName: "Senthil Kumar",
    email: "senthil@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["admin", "product_manager"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2026-03-25T09:00:00Z",
  },
  {
    id: "usr-002",
    fullName: "Ahmed Hassan",
    email: "ahmed.hassan@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["product_manager"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-03-15T10:00:00Z",
    updatedAt: "2026-03-24T14:00:00Z",
  },
  {
    id: "usr-003",
    fullName: "Sarah Ahmed",
    email: "sarah.ahmed@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["content_reviewer", "classification_reviewer"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: "2025-05-20T09:00:00Z",
    updatedAt: "2026-03-25T08:30:00Z",
  },
  {
    id: "usr-004",
    fullName: "Fatima Al-Rashid",
    email: "fatima.r@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["content_reviewer"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2026-03-23T16:00:00Z",
  },
  {
    id: "usr-005",
    fullName: "Raj Patel",
    email: "raj.patel@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["classification_reviewer"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-08-10T10:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
  },
  {
    id: "usr-006",
    fullName: "Omar Khalil",
    email: "omar.k@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["read_only"],
    status: "inactive",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-09-05T10:00:00Z",
    updatedAt: "2026-02-15T12:00:00Z",
  },
  {
    id: "usr-007",
    fullName: "Priya Nair",
    email: "priya.nair@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["product_manager", "content_reviewer"],
    status: "suspended",
    suspendedReason: "Unauthorized data export attempt detected",
    suspendedAt: "2026-03-20T14:30:00Z",
    lastLogin: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-06-12T10:00:00Z",
    updatedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "usr-008",
    fullName: "David Chen",
    email: "david.chen@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["admin"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: "2025-02-01T08:00:00Z",
    updatedAt: "2026-03-25T07:00:00Z",
  },
  {
    id: "usr-009",
    fullName: "Layla Mahmoud",
    email: "layla.m@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["product_manager"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: null,
    createdAt: "2026-03-24T10:00:00Z",
    updatedAt: "2026-03-24T10:00:00Z",
  },
  {
    id: "usr-010",
    fullName: "Ali Reza",
    email: "ali.reza@raynatours.com",
    avatarUrl: null,
    profilePictureUrl: null,
    jobTitle: null,
    department: null,
    phone: null,
    timezone: null,
    roles: ["read_only"],
    status: "active",
    suspendedReason: null,
    suspendedAt: null,
    lastLogin: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2026-03-21T09:00:00Z",
  },
];

// ---- Role History ----
export const MOCK_ROLE_HISTORY: RoleHistoryEntry[] = [
  {
    id: "rh-001",
    userId: "usr-003",
    action: "added",
    role: "classification_reviewer",
    performedBy: "senthil@raynatours.com",
    performedAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "rh-002",
    userId: "usr-003",
    action: "added",
    role: "content_reviewer",
    performedBy: "senthil@raynatours.com",
    performedAt: "2025-05-20T09:00:00Z",
  },
  {
    id: "rh-003",
    userId: "usr-007",
    action: "removed",
    role: "admin",
    performedBy: "senthil@raynatours.com",
    performedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "rh-004",
    userId: "usr-002",
    action: "added",
    role: "product_manager",
    performedBy: "senthil@raynatours.com",
    performedAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "rh-005",
    userId: "usr-001",
    action: "added",
    role: "admin",
    performedBy: "david.chen@raynatours.com",
    performedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "rh-006",
    userId: "usr-008",
    action: "added",
    role: "admin",
    performedBy: "senthil@raynatours.com",
    performedAt: "2025-02-01T08:00:00Z",
  },
  {
    id: "rh-007",
    userId: "usr-004",
    action: "added",
    role: "content_reviewer",
    performedBy: "ahmed.hassan@raynatours.com",
    performedAt: "2025-07-01T10:00:00Z",
  },
];

// ---- Activity Log ----
export const MOCK_USER_ACTIVITY: UserActivityEntry[] = [
  {
    id: "act-001",
    userId: "usr-002",
    action: "Approved staging batch",
    entity: "batch-001 (Dubai)",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-002",
    userId: "usr-002",
    action: "Triggered ingestion run",
    entity: "Dubai - Full Sync",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-003",
    userId: "usr-002",
    action: "Updated product attributes",
    entity: "Burj Khalifa Observation Deck",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-004",
    userId: "usr-002",
    action: "Created package",
    entity: "Dubai Premium 5-Day",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-005",
    userId: "usr-002",
    action: "Rejected staging batch",
    entity: "batch-006 (Abu Dhabi)",
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-006",
    userId: "usr-003",
    action: "Reviewed classification",
    entity: "prod-dubai-a456",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-007",
    userId: "usr-003",
    action: "Approved content",
    entity: "Desert Safari Premium",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-008",
    userId: "usr-003",
    action: "Rejected content",
    entity: "Airport Transfer DXB",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-009",
    userId: "usr-003",
    action: "Reviewed classification",
    entity: "prod-istanbul-a678",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-010",
    userId: "usr-003",
    action: "Approved content",
    entity: "La Petite Maison",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-011",
    userId: "usr-001",
    action: "Suspended user",
    entity: "Priya Nair (usr-007)",
    timestamp: "2026-03-20T14:30:00Z",
  },
  {
    id: "act-012",
    userId: "usr-001",
    action: "Invited user",
    entity: "Layla Mahmoud (layla.m@raynatours.com)",
    timestamp: "2026-03-24T10:00:00Z",
  },
  {
    id: "act-013",
    userId: "usr-004",
    action: "Approved content",
    entity: "Tbilisi Food Tour",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-014",
    userId: "usr-005",
    action: "Reviewed classification",
    entity: "prod-maldives-r345",
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
];
