import type {
  AttributeProduct,
  EnrichmentQueueEntry,
  HotelAttributes,
  AttractionAttributes,
  TransferAttributes,
  RestaurantAttributes,
} from "@/types/attributes";

// ---- HOTELS ----
const hotelProducts: AttributeProduct[] = [
  {
    id: "attr-h-001",
    name: "Atlantis The Palm",
    destination: "Dubai",
    category: "hotels",
    status: "published",
    completeness: 95,
    missingFields: ["metaDescription"],
    updatedAt: "2025-03-20T10:30:00Z",
    attributes: {
      hotelName: "Atlantis The Palm",
      starRating: 5,
      propertyType: "Resort",
      status: "published",
      address: "Crescent Rd, The Palm Jumeirah",
      latitude: 25.1304,
      longitude: 55.1172,
      destination: "Dubai",
      checkInTime: "15:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Free",
      roomTypes: ["Standard", "Deluxe", "Suite", "Family"],
      boardTypes: ["BB", "HB", "FB"],
      amenities: ["a1", "a2", "a3", "a5", "a6", "a9", "a10", "a11", "a14", "a18", "a20"],
      netRateFrom: 1850,
      currencyCode: "AED",
      bookingSources: ["Booking.com", "Expedia", "Direct"],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400" },
        { id: "img6", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400" },
      ],
      shortDescription: "Iconic 5-star resort on the crescent of Palm Jumeirah with luxury rooms, aquapark, and aquarium.",
      metaTitle: "Atlantis The Palm Dubai – Luxury Resort & Waterpark",
      metaDescription: "",
      contentStatus: "Approved",
      tags: [
        { dimension: "budget_tier", value: "Luxury" },
        { dimension: "travel_theme", value: "Beach & Resort" },
        { dimension: "audience", value: "Families" },
      ],
    } as HotelAttributes,
  },
  {
    id: "attr-h-002",
    name: "Burj Al Arab Jumeirah",
    destination: "Dubai",
    category: "hotels",
    status: "published",
    completeness: 100,
    missingFields: [],
    updatedAt: "2025-03-18T14:00:00Z",
    attributes: {
      hotelName: "Burj Al Arab Jumeirah",
      starRating: 5,
      propertyType: "Hotel",
      status: "published",
      address: "Jumeirah Street, Umm Suqeim 3",
      latitude: 25.1412,
      longitude: 55.1853,
      destination: "Dubai",
      checkInTime: "15:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Partial",
      roomTypes: ["Deluxe", "Suite"],
      boardTypes: ["BB", "HB", "FB", "AI"],
      amenities: ["a1", "a2", "a3", "a6", "a7", "a9", "a10", "a11", "a14", "a18", "a19", "a20", "a22"],
      netRateFrom: 5200,
      currencyCode: "AED",
      bookingSources: ["Direct", "Luxury Escapes"],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1570213489059-0aac6626cade?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1606046604972-77cc76aee944?w=400" },
      ],
      shortDescription: "The world's most luxurious hotel, a sail-shaped icon on its own island off Jumeirah Beach.",
      metaTitle: "Burj Al Arab – World's Most Luxurious Hotel in Dubai",
      metaDescription: "Experience unmatched luxury at Burj Al Arab Jumeirah. Iconic sail-shaped hotel with duplex suites, private beach, and world-class dining.",
      contentStatus: "Approved",
      tags: [
        { dimension: "budget_tier", value: "Ultra Luxury" },
        { dimension: "travel_theme", value: "Beach & Resort" },
        { dimension: "audience", value: "Couples" },
      ],
    } as HotelAttributes,
  },
  {
    id: "attr-h-003",
    name: "Rove Downtown",
    destination: "Dubai",
    category: "hotels",
    status: "staged",
    completeness: 72,
    missingFields: ["metaTitle", "metaDescription", "amenities"],
    updatedAt: "2025-03-15T09:00:00Z",
    attributes: {
      hotelName: "Rove Downtown",
      starRating: 3,
      propertyType: "Hotel",
      status: "staged",
      address: "Financial Center Road, Downtown",
      latitude: 25.2048,
      longitude: 55.2708,
      destination: "Dubai",
      checkInTime: "14:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Free",
      roomTypes: ["Standard", "Family"],
      boardTypes: ["RO", "BB"],
      amenities: ["a1", "a3", "a14"],
      netRateFrom: 380,
      currencyCode: "AED",
      bookingSources: ["Booking.com", "Agoda"],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400" },
      ],
      shortDescription: "Affordable and trendy hotel in the heart of Downtown Dubai, steps from Dubai Mall.",
      metaTitle: "",
      metaDescription: "",
      contentStatus: "Draft",
      tags: [
        { dimension: "budget_tier", value: "Mid-Range" },
        { dimension: "travel_theme", value: "City Explorer" },
      ],
    } as HotelAttributes,
  },
  {
    id: "attr-h-004",
    name: "Jumeirah Al Qasr",
    destination: "Dubai",
    category: "hotels",
    status: "draft",
    completeness: 45,
    missingFields: ["checkInTime", "checkOutTime", "roomTypes", "boardTypes", "amenities", "images", "metaTitle", "metaDescription"],
    updatedAt: "2025-03-10T11:00:00Z",
    attributes: {
      hotelName: "Jumeirah Al Qasr",
      starRating: 5,
      propertyType: "Resort",
      status: "draft",
      address: "Al Sufouh Road, Madinat Jumeirah",
      latitude: 25.1324,
      longitude: 55.1857,
      destination: "Dubai",
      checkInTime: "",
      checkOutTime: "",
      cancellationPolicy: "Partial",
      roomTypes: [],
      boardTypes: [],
      amenities: [],
      netRateFrom: 2400,
      currencyCode: "AED",
      bookingSources: ["Direct"],
      images: [],
      shortDescription: "Arabian palace-inspired luxury resort within Madinat Jumeirah.",
      metaTitle: "",
      metaDescription: "",
      contentStatus: "Draft",
      tags: [
        { dimension: "budget_tier", value: "Luxury" },
      ],
    } as HotelAttributes,
  },
  {
    id: "attr-h-005",
    name: "Shangri-La Muscat",
    destination: "Muscat",
    category: "hotels",
    status: "published",
    completeness: 88,
    missingFields: ["metaDescription"],
    updatedAt: "2025-03-12T16:00:00Z",
    attributes: {
      hotelName: "Shangri-La Barr Al Jissah",
      starRating: 5,
      propertyType: "Resort",
      status: "published",
      address: "Barr Al Jissah, Muscat",
      latitude: 23.5475,
      longitude: 58.6498,
      destination: "Muscat",
      checkInTime: "15:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Partial",
      roomTypes: ["Standard", "Deluxe", "Suite"],
      boardTypes: ["BB", "HB", "FB"],
      amenities: ["a1", "a2", "a3", "a5", "a6", "a9", "a10", "a14", "a18"],
      netRateFrom: 120,
      currencyCode: "OMR",
      bookingSources: ["Booking.com", "Direct"],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400" },
      ],
      shortDescription: "Luxury beachfront resort set against dramatic mountain backdrop in Oman's capital.",
      metaTitle: "Shangri-La Barr Al Jissah – Beach Resort Muscat",
      metaDescription: "",
      contentStatus: "Approved",
      tags: [
        { dimension: "budget_tier", value: "Luxury" },
        { dimension: "travel_theme", value: "Beach & Resort" },
        { dimension: "audience", value: "Families" },
      ],
    } as HotelAttributes,
  },
  {
    id: "attr-h-006",
    name: "W Abu Dhabi – Yas Island",
    destination: "Abu Dhabi",
    category: "hotels",
    status: "staged",
    completeness: 80,
    missingFields: ["images", "metaDescription"],
    updatedAt: "2025-03-08T13:30:00Z",
    attributes: {
      hotelName: "W Abu Dhabi – Yas Island",
      starRating: 5,
      propertyType: "Hotel",
      status: "staged",
      address: "Yas Island",
      latitude: 24.4672,
      longitude: 54.6073,
      destination: "Abu Dhabi",
      checkInTime: "15:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Free",
      roomTypes: ["Standard", "Deluxe", "Suite"],
      boardTypes: ["BB", "HB"],
      amenities: ["a1", "a2", "a3", "a6", "a9", "a10", "a14", "a18"],
      netRateFrom: 950,
      currencyCode: "AED",
      bookingSources: ["Marriott", "Booking.com"],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400" },
      ],
      shortDescription: "Futuristic design hotel on Yas Island with stunning views of Yas Marina Circuit.",
      metaTitle: "W Abu Dhabi Yas Island – Design Hotel F1 Circuit",
      metaDescription: "",
      contentStatus: "Draft",
      tags: [
        { dimension: "budget_tier", value: "Luxury" },
        { dimension: "travel_theme", value: "City Explorer" },
      ],
    } as HotelAttributes,
  },
];

// ---- ATTRACTIONS ----
const attractionProducts: AttributeProduct[] = [
  {
    id: "attr-a-001",
    name: "Burj Khalifa At The Top",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 92,
    missingFields: ["metaDescription"],
    updatedAt: "2025-03-19T08:00:00Z",
    attributes: {
      attractionName: "Burj Khalifa At The Top",
      category: "Entertainment",
      address: "1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai",
      latitude: 25.1972,
      longitude: 55.2744,
      destination: "Dubai",
      typicalDuration: "1–2 hours",
      minimumAge: 0,
      includesText: "Access to observation deck levels 124 & 125, multimedia presentation, free WiFi",
      excludesText: "Food & beverages, souvenir photos, level 148 SKY access",
      operatingHours: [
        { day: "Sunday", openTime: "10:00", closeTime: "22:00", closed: false },
        { day: "Monday", openTime: "10:00", closeTime: "22:00", closed: false },
        { day: "Tuesday", openTime: "10:00", closeTime: "22:00", closed: false },
        { day: "Wednesday", openTime: "10:00", closeTime: "22:00", closed: false },
        { day: "Thursday", openTime: "10:00", closeTime: "23:00", closed: false },
        { day: "Friday", openTime: "10:00", closeTime: "23:00", closed: false },
        { day: "Saturday", openTime: "10:00", closeTime: "23:00", closed: false },
      ],
      lastVerifiedDate: "2025-03-14",
      ticketTypes: [
        { id: "t1", type: "Adult", priceFrom: 169, priceTo: 399, currency: "AED" },
        { id: "t2", type: "Child", priceFrom: 120, priceTo: 299, currency: "AED" },
      ],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1597659840241-37e2b9c2f55f?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1546412414-e1885259563a?w=400" },
      ],
      shortDescription: "Visit the world's tallest building observation deck for breathtaking 360° views of Dubai.",
      metaTitle: "Burj Khalifa At The Top – Tickets & Prices 2025",
      metaDescription: "",
      contentStatus: "Approved",
      tags: [
        { dimension: "budget_tier", value: "Mid-Range" },
        { dimension: "travel_theme", value: "City Explorer" },
        { dimension: "audience", value: "Families" },
      ],
    } as AttractionAttributes,
  },
  {
    id: "attr-a-002",
    name: "Dubai Aquaventure Waterpark",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 98,
    missingFields: [],
    updatedAt: "2025-03-17T11:00:00Z",
    attributes: {
      attractionName: "Aquaventure Waterpark",
      category: "Water",
      address: "Atlantis The Palm, Crescent Rd",
      latitude: 25.1304,
      longitude: 55.1172,
      destination: "Dubai",
      typicalDuration: "4–6 hours",
      minimumAge: 0,
      includesText: "Access to all rides, Aquaventure Beach, The Lost Chambers Aquarium",
      excludesText: "Locker rental, towel rental, food & beverages, dolphin encounters",
      operatingHours: [
        { day: "Sunday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Monday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Tuesday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Wednesday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Thursday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Friday", openTime: "10:00", closeTime: "18:00", closed: false },
        { day: "Saturday", openTime: "10:00", closeTime: "18:00", closed: false },
      ],
      lastVerifiedDate: "2025-03-10",
      ticketTypes: [
        { id: "t1", type: "Adult", priceFrom: 299, priceTo: 399, currency: "AED" },
        { id: "t2", type: "Child", priceFrom: 249, priceTo: 349, currency: "AED" },
        { id: "t3", type: "Family", priceFrom: 999, priceTo: 1399, currency: "AED" },
      ],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1559599189-fe84dea4eb79?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400" },
      ],
      shortDescription: "World's largest waterpark with record-breaking slides, a private beach, and marine encounters.",
      metaTitle: "Aquaventure Waterpark – World's Largest Waterpark Dubai",
      metaDescription: "Experience thrilling slides and attractions at Aquaventure Waterpark at Atlantis The Palm, Dubai.",
      contentStatus: "Approved",
      tags: [
        { dimension: "budget_tier", value: "Mid-Range" },
        { dimension: "travel_theme", value: "Adventure" },
        { dimension: "audience", value: "Families" },
      ],
    } as AttractionAttributes,
  },
  {
    id: "attr-a-003",
    name: "Louvre Abu Dhabi",
    destination: "Abu Dhabi",
    category: "attractions",
    status: "published",
    completeness: 85,
    missingFields: ["excludesText", "metaDescription"],
    updatedAt: "2025-03-14T09:30:00Z",
    attributes: {
      attractionName: "Louvre Abu Dhabi",
      category: "Cultural",
      address: "Saadiyat Island, Abu Dhabi",
      latitude: 24.5335,
      longitude: 54.3983,
      destination: "Abu Dhabi",
      typicalDuration: "2–3 hours",
      minimumAge: 0,
      includesText: "Museum general admission, temporary exhibitions, multimedia guide",
      excludesText: "",
      operatingHours: [
        { day: "Sunday", openTime: "10:00", closeTime: "18:30", closed: false },
        { day: "Monday", openTime: "00:00", closeTime: "00:00", closed: true },
        { day: "Tuesday", openTime: "10:00", closeTime: "18:30", closed: false },
        { day: "Wednesday", openTime: "10:00", closeTime: "18:30", closed: false },
        { day: "Thursday", openTime: "10:00", closeTime: "18:30", closed: false },
        { day: "Friday", openTime: "10:00", closeTime: "18:30", closed: false },
        { day: "Saturday", openTime: "10:00", closeTime: "20:30", closed: false },
      ],
      lastVerifiedDate: "2025-02-28",
      ticketTypes: [
        { id: "t1", type: "Adult", priceFrom: 63, priceTo: 63, currency: "AED" },
        { id: "t2", type: "Child", priceFrom: 0, priceTo: 0, currency: "AED" },
        { id: "t3", type: "Senior", priceFrom: 31, priceTo: 31, currency: "AED" },
      ],
      images: [
        { id: "img1", url: "https://images.unsplash.com/photo-1583396060293-6b9ef4025a7a?w=400" },
        { id: "img2", url: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400" },
        { id: "img3", url: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=400" },
        { id: "img4", url: "https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=400" },
        { id: "img5", url: "https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=400" },
      ],
      shortDescription: "Architectural masterpiece museum on Saadiyat Island showcasing art from ancient to contemporary.",
      metaTitle: "Louvre Abu Dhabi – Museum Tickets & Info",
      metaDescription: "",
      contentStatus: "Needs Refresh",
      tags: [
        { dimension: "budget_tier", value: "Budget" },
        { dimension: "travel_theme", value: "Cultural" },
      ],
    } as AttractionAttributes,
  },
  {
    id: "attr-a-004",
    name: "Desert Safari Adventure",
    destination: "Dubai",
    category: "attractions",
    status: "draft",
    completeness: 55,
    missingFields: ["includesText", "excludesText", "operatingHours", "ticketTypes", "images"],
    updatedAt: "2025-03-05T14:00:00Z",
    attributes: {
      attractionName: "Desert Safari Adventure",
      category: "Adventure",
      address: "Dubai Desert Conservation Reserve",
      latitude: 24.9500,
      longitude: 55.6500,
      destination: "Dubai",
      typicalDuration: "6–7 hours",
      minimumAge: 3,
      includesText: "",
      excludesText: "",
      operatingHours: [
        { day: "Sunday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Monday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Tuesday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Wednesday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Thursday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Friday", openTime: "15:00", closeTime: "21:00", closed: false },
        { day: "Saturday", openTime: "15:00", closeTime: "21:00", closed: false },
      ],
      lastVerifiedDate: "2025-01-15",
      ticketTypes: [],
      images: [],
      shortDescription: "Thrilling dune bashing, camel rides, and BBQ dinner under the stars in the Arabian desert.",
      metaTitle: "Dubai Desert Safari – Adventure Tours",
      metaDescription: "",
      contentStatus: "Draft",
      tags: [
        { dimension: "travel_theme", value: "Adventure" },
      ],
    } as AttractionAttributes,
  },
];

// ---- TRANSFERS ----
const transferProducts: AttributeProduct[] = [
  {
    id: "attr-t-001",
    name: "DXB Airport → Downtown Hotels",
    destination: "Dubai",
    category: "transfers",
    status: "published",
    completeness: 100,
    missingFields: [],
    updatedAt: "2025-03-21T07:00:00Z",
    attributes: {
      transferName: "DXB Airport to Downtown Hotels",
      transferType: "Airport",
      originLocation: "Dubai International Airport (DXB)",
      destinationLocation: "Downtown Dubai Hotels",
      typicalDuration: "25–40 min",
      vehicleType: "Sedan",
      minPax: 1,
      maxPax: 3,
      pricingModel: "Per Vehicle",
      netRate: 180,
      currencyCode: "AED",
      meetAndGreet: true,
      availability247: true,
      flightMonitoring: true,
      shortDescription: "Private airport transfer from DXB Terminal to Downtown Dubai hotels with meet & greet.",
      tags: [
        { dimension: "budget_tier", value: "Mid-Range" },
        { dimension: "audience", value: "Business" },
      ],
    } as TransferAttributes,
  },
  {
    id: "attr-t-002",
    name: "DXB Airport → Palm Jumeirah",
    destination: "Dubai",
    category: "transfers",
    status: "published",
    completeness: 95,
    missingFields: ["shortDescription"],
    updatedAt: "2025-03-20T12:00:00Z",
    attributes: {
      transferName: "DXB Airport to Palm Jumeirah Hotels",
      transferType: "Airport",
      originLocation: "Dubai International Airport (DXB)",
      destinationLocation: "Palm Jumeirah Hotels",
      typicalDuration: "35–50 min",
      vehicleType: "Van",
      minPax: 1,
      maxPax: 6,
      pricingModel: "Per Vehicle",
      netRate: 250,
      currencyCode: "AED",
      meetAndGreet: true,
      availability247: true,
      flightMonitoring: true,
      shortDescription: "",
      tags: [
        { dimension: "budget_tier", value: "Mid-Range" },
      ],
    } as TransferAttributes,
  },
  {
    id: "attr-t-003",
    name: "Dubai → Abu Dhabi City",
    destination: "Dubai",
    category: "transfers",
    status: "staged",
    completeness: 82,
    missingFields: ["shortDescription"],
    updatedAt: "2025-03-15T10:00:00Z",
    attributes: {
      transferName: "Dubai to Abu Dhabi Intercity Transfer",
      transferType: "Intercity",
      originLocation: "Dubai (any hotel)",
      destinationLocation: "Abu Dhabi (any hotel)",
      typicalDuration: "1.5–2 hours",
      vehicleType: "Sedan",
      minPax: 1,
      maxPax: 3,
      pricingModel: "Per Vehicle",
      netRate: 450,
      currencyCode: "AED",
      meetAndGreet: false,
      availability247: false,
      flightMonitoring: false,
      shortDescription: "",
      tags: [],
    } as TransferAttributes,
  },
  {
    id: "attr-t-004",
    name: "Muscat Airport → City Hotels",
    destination: "Muscat",
    category: "transfers",
    status: "draft",
    completeness: 60,
    missingFields: ["vehicleType", "shortDescription", "tags"],
    updatedAt: "2025-03-01T08:00:00Z",
    attributes: {
      transferName: "Muscat International Airport to City Hotels",
      transferType: "Airport",
      originLocation: "Muscat International Airport",
      destinationLocation: "Muscat City Hotels",
      typicalDuration: "20–30 min",
      vehicleType: "Sedan",
      minPax: 1,
      maxPax: 3,
      pricingModel: "Per Vehicle",
      netRate: 15,
      currencyCode: "OMR",
      meetAndGreet: true,
      availability247: true,
      flightMonitoring: true,
      shortDescription: "",
      tags: [],
    } as TransferAttributes,
  },
  {
    id: "attr-t-005",
    name: "Dubai Marina Cruise Transfer",
    destination: "Dubai",
    category: "transfers",
    status: "published",
    completeness: 90,
    missingFields: [],
    updatedAt: "2025-03-18T15:00:00Z",
    attributes: {
      transferName: "Dubai Marina Cruise Port Transfer",
      transferType: "Port",
      originLocation: "Dubai Marina Cruise Terminal",
      destinationLocation: "Dubai Hotels (any)",
      typicalDuration: "15–45 min",
      vehicleType: "Minibus",
      minPax: 1,
      maxPax: 12,
      pricingModel: "Per Person",
      netRate: 55,
      currencyCode: "AED",
      meetAndGreet: true,
      availability247: false,
      flightMonitoring: false,
      shortDescription: "Comfortable group transfer from Dubai Marina Cruise Terminal to your hotel.",
      tags: [
        { dimension: "budget_tier", value: "Budget" },
      ],
    } as TransferAttributes,
  },
];

// ---- RESTAURANTS ----
const restaurantProducts: AttributeProduct[] = [
  {
    id: "attr-r-001",
    name: "Nobu Dubai",
    destination: "Dubai",
    category: "restaurants",
    status: "published",
    completeness: 90,
    missingFields: [],
    updatedAt: "2025-03-19T12:00:00Z",
    attributes: {
      restaurantName: "Nobu Dubai",
      cuisineType: "Japanese-Peruvian Fusion",
      priceRange: "$$$$",
      address: "Atlantis The Palm, Crescent Rd",
      latitude: 25.1304,
      longitude: 55.1172,
      destination: "Dubai",
      operatingHours: [
        { day: "Sunday", openTime: "18:00", closeTime: "23:30", closed: false },
        { day: "Monday", openTime: "18:00", closeTime: "23:30", closed: false },
        { day: "Tuesday", openTime: "18:00", closeTime: "23:30", closed: false },
        { day: "Wednesday", openTime: "18:00", closeTime: "23:30", closed: false },
        { day: "Thursday", openTime: "18:00", closeTime: "00:00", closed: false },
        { day: "Friday", openTime: "12:30", closeTime: "00:00", closed: false },
        { day: "Saturday", openTime: "12:30", closeTime: "00:00", closed: false },
      ],
      tags: [
        { dimension: "budget_tier", value: "Luxury" },
        { dimension: "travel_theme", value: "Fine Dining" },
      ],
    } as RestaurantAttributes,
  },
  {
    id: "attr-r-002",
    name: "Al Mahara",
    destination: "Dubai",
    category: "restaurants",
    status: "published",
    completeness: 85,
    missingFields: [],
    updatedAt: "2025-03-16T10:00:00Z",
    attributes: {
      restaurantName: "Al Mahara",
      cuisineType: "Seafood",
      priceRange: "$$$$",
      address: "Burj Al Arab, Jumeirah Street",
      latitude: 25.1412,
      longitude: 55.1853,
      destination: "Dubai",
      operatingHours: [
        { day: "Sunday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Monday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Tuesday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Wednesday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Thursday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Friday", openTime: "12:30", closeTime: "15:00", closed: false },
        { day: "Saturday", openTime: "12:30", closeTime: "15:00", closed: false },
      ],
      tags: [
        { dimension: "budget_tier", value: "Ultra Luxury" },
        { dimension: "travel_theme", value: "Fine Dining" },
      ],
    } as RestaurantAttributes,
  },
];

// ---- Combined export by category ----
export const MOCK_ATTRIBUTE_PRODUCTS: Record<string, AttributeProduct[]> = {
  hotels: hotelProducts,
  attractions: attractionProducts,
  transfers: transferProducts,
  restaurants: restaurantProducts,
};

// ---- Enrichment Queue ----
export const MOCK_ENRICHMENT_QUEUE: EnrichmentQueueEntry[] = [
  {
    id: "eq-001",
    productId: "attr-h-004",
    productName: "Jumeirah Al Qasr",
    category: "hotels",
    missingFields: ["checkInTime", "checkOutTime", "roomTypes", "boardTypes", "amenities", "images"],
    assignedTo: "Sarah M.",
    priority: "high",
    createdAt: "2025-03-10T11:00:00Z",
  },
  {
    id: "eq-002",
    productId: "attr-a-004",
    productName: "Desert Safari Adventure",
    category: "attractions",
    missingFields: ["includesText", "excludesText", "ticketTypes", "images"],
    assignedTo: "Ahmed K.",
    priority: "high",
    createdAt: "2025-03-05T14:00:00Z",
  },
  {
    id: "eq-003",
    productId: "attr-h-003",
    productName: "Rove Downtown",
    category: "hotels",
    missingFields: ["metaTitle", "metaDescription", "amenities"],
    assignedTo: "Sarah M.",
    priority: "medium",
    createdAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "eq-004",
    productId: "attr-t-004",
    productName: "Muscat Airport → City Hotels",
    category: "transfers",
    missingFields: ["vehicleType", "shortDescription", "tags"],
    assignedTo: "Unassigned",
    priority: "medium",
    createdAt: "2025-03-01T08:00:00Z",
  },
  {
    id: "eq-005",
    productId: "attr-h-006",
    productName: "W Abu Dhabi – Yas Island",
    category: "hotels",
    missingFields: ["images", "metaDescription"],
    assignedTo: "Maria L.",
    priority: "low",
    createdAt: "2025-03-08T13:30:00Z",
  },
  {
    id: "eq-006",
    productId: "attr-a-003",
    productName: "Louvre Abu Dhabi",
    category: "attractions",
    missingFields: ["excludesText", "metaDescription"],
    assignedTo: "Ahmed K.",
    priority: "low",
    createdAt: "2025-03-14T09:30:00Z",
  },
  {
    id: "eq-007",
    productId: "attr-t-002",
    productName: "DXB Airport → Palm Jumeirah",
    category: "transfers",
    missingFields: ["shortDescription"],
    assignedTo: "Unassigned",
    priority: "low",
    createdAt: "2025-03-20T12:00:00Z",
  },
  {
    id: "eq-008",
    productId: "attr-h-001",
    productName: "Atlantis The Palm",
    category: "hotels",
    missingFields: ["metaDescription"],
    assignedTo: "Maria L.",
    priority: "low",
    createdAt: "2025-03-20T10:30:00Z",
  },
  {
    id: "eq-009",
    productId: "attr-h-005",
    productName: "Shangri-La Muscat",
    category: "hotels",
    missingFields: ["metaDescription"],
    assignedTo: "Unassigned",
    priority: "low",
    createdAt: "2025-03-12T16:00:00Z",
  },
  {
    id: "eq-010",
    productId: "attr-t-003",
    productName: "Dubai → Abu Dhabi City",
    category: "transfers",
    missingFields: ["shortDescription"],
    assignedTo: "Unassigned",
    priority: "low",
    createdAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "eq-011",
    productId: "attr-r-001",
    productName: "Nobu Dubai",
    category: "restaurants",
    missingFields: [],
    assignedTo: "Sarah M.",
    priority: "low",
    createdAt: "2025-03-19T12:00:00Z",
  },
  {
    id: "eq-012",
    productId: "attr-r-002",
    productName: "Al Mahara",
    category: "restaurants",
    missingFields: [],
    assignedTo: "Ahmed K.",
    priority: "low",
    createdAt: "2025-03-16T10:00:00Z",
  },
];
