import type { Product } from "@/types/products";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    name: "Atlantis The Palm",
    destination: "Dubai",
    category: "hotels",
    status: "published",
    completeness: 95,
    heroImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600",
    tags: [
      { dimension: "budget_tier", value: "Luxury" },
      { dimension: "travel_theme", value: "Beach & Resort" },
      { dimension: "audience", value: "Families" },
      { dimension: "season", value: "Year-round" },
      { dimension: "accessibility", value: "Wheelchair Accessible" },
    ],
    bookingSource: { id: "booking", name: "Booking.com", url: "https://booking.com/hotel/ae/atlantis-the-palm" },
    publishFlag: true,
    attributes: {
      location: { address: "Crescent Rd, The Palm Jumeirah", city: "Dubai", country: "UAE", latitude: 25.1304, longitude: 55.1172 },
      pricing: { currency: "AED", amount: 1850, per: "night" },
      starRating: 5,
      duration: null,
      operatingHours: "24/7",
      contactPhone: "+971 4 426 2000",
      contactEmail: "reservations@atlantisthepalm.com",
      website: "https://www.atlantis.com/dubai",
    },
    content: {
      shortDesc: "Iconic 5-star resort on the crescent of Palm Jumeirah with luxury rooms, aquapark, and aquarium.",
      longDesc: "Atlantis The Palm is a world-renowned luxury resort situated on the crescent of the Palm Jumeirah. The resort features 1,548 rooms and suites, each offering stunning views of the Arabian Sea or The Palm. Guests enjoy access to Aquaventure Waterpark, The Lost Chambers Aquarium, and over 30 dining options including Nobu and Ossiano.",
      metaTitle: "Atlantis The Palm Dubai | 5-Star Luxury Resort on Palm Jumeirah",
      metaDescription: "Experience luxury at Atlantis The Palm Dubai. Enjoy world-class dining, Aquaventure Waterpark, and stunning ocean views. Book your stay today.",
      faq: [
        { question: "Does Atlantis The Palm have a private beach?", answer: "Yes, the resort features a pristine private beach exclusively for hotel guests." },
        { question: "Is Aquaventure Waterpark included?", answer: "Yes, all hotel guests receive complimentary access to Aquaventure Waterpark during their stay." },
      ],
      schemaMarkup: '{"@type":"Hotel","name":"Atlantis The Palm","starRating":{"ratingValue":"5"}}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600",
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600",
      ],
      videos: ["https://www.youtube.com/watch?v=example1"],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "All required content fields are filled", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image meets minimum resolution", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "Meta title and description meet SEO guidelines", status: "pass", details: "Score: 92/100", checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-4", name: "Pricing Validation", description: "Pricing data is current and valid", status: "warning", details: "Price last updated 5 days ago", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Product published to live catalog", user: "Admin", timestamp: "2026-03-23T14:00:00Z" },
      { id: "h-2", action: "content_generated", description: "AI content generation completed (attempt 2)", user: "System", timestamp: "2026-03-22T09:30:00Z" },
      { id: "h-3", action: "tags_updated", description: "Tags updated: added Wheelchair Accessible", user: "Sarah M.", timestamp: "2026-03-21T11:00:00Z" },
      { id: "h-4", action: "created", description: "Product ingested from Booking.com", user: "System", timestamp: "2026-03-20T08:00:00Z" },
    ],
    createdAt: "2026-03-20T08:00:00Z",
    updatedAt: "2026-03-23T14:00:00Z",
  },
  {
    id: "prod-002",
    name: "Burj Khalifa At The Top",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 88,
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Sightseeing" },
      { dimension: "audience", value: "Couples" },
      { dimension: "audience", value: "Families" },
    ],
    bookingSource: { id: "viator", name: "Viator", url: "https://viator.com/tours/Dubai/Burj-Khalifa" },
    publishFlag: true,
    attributes: {
      location: { address: "1 Sheikh Mohammed bin Rashid Blvd", city: "Dubai", country: "UAE", latitude: 25.1972, longitude: 55.2744 },
      pricing: { currency: "AED", amount: 169, per: "person" },
      starRating: null,
      duration: "1.5 hours",
      operatingHours: "10:00 AM - 10:00 PM",
      contactPhone: "+971 4 888 8888",
      contactEmail: null,
      website: "https://www.burjkhalifa.ae",
    },
    content: {
      shortDesc: "Visit the observation deck of the world's tallest building for breathtaking 360° views of Dubai.",
      longDesc: "At The Top, Burj Khalifa offers visitors the chance to experience the world from the 124th and 125th floors of the iconic Burj Khalifa. Standing at 828 meters, the observation deck provides unparalleled panoramic views of the city, the desert, and the ocean beyond.",
      metaTitle: "Burj Khalifa At The Top Tickets | Dubai Observation Deck",
      metaDescription: "Book Burj Khalifa At The Top tickets. Experience breathtaking views from the 124th floor of the world's tallest building.",
      faq: [
        { question: "How long is the visit?", answer: "Plan for approximately 1.5 hours including the elevator ride and observation time." },
      ],
      schemaMarkup: '{"@type":"TouristAttraction","name":"Burj Khalifa At The Top"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600",
        "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "All required fields filled", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image resolution check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "SEO guidelines check", status: "pass", details: "Score: 87/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-22T16:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Viator", user: "System", timestamp: "2026-03-19T07:00:00Z" },
    ],
    createdAt: "2026-03-19T07:00:00Z",
    updatedAt: "2026-03-22T16:00:00Z",
  },
  {
    id: "prod-003",
    name: "Dubai Airport Transfer – Private Sedan",
    destination: "Dubai",
    category: "transfers",
    status: "staged",
    completeness: 72,
    heroImage: null,
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Transport" },
      { dimension: "audience", value: "Business" },
    ],
    bookingSource: { id: "hotelbeds", name: "Hotelbeds", url: "https://hotelbeds.com/transfers/dubai-airport" },
    publishFlag: false,
    attributes: {
      location: { address: "Dubai International Airport (DXB)", city: "Dubai", country: "UAE", latitude: 25.2532, longitude: 55.3657 },
      pricing: { currency: "AED", amount: 220, per: "vehicle" },
      starRating: null,
      duration: "30-60 minutes",
      operatingHours: "24/7",
      contactPhone: null,
      contactEmail: "transfers@raynatours.com",
      website: null,
    },
    content: {
      shortDesc: "Private sedan transfer from Dubai International Airport to any hotel in Dubai.",
      longDesc: "Enjoy a comfortable and stress-free private sedan transfer from Dubai International Airport (DXB) to your hotel. Professional English-speaking drivers, meet & greet service, and complimentary waiting time included.",
      metaTitle: "Dubai Airport Transfer | Private Sedan Service",
      metaDescription: "Book a private sedan transfer from Dubai Airport. Professional drivers, meet & greet, and door-to-door service.",
      faq: [],
      schemaMarkup: "",
    },
    media: { images: [], videos: [] },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "warning", details: "Missing FAQ and schema markup", checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "fail", details: "No hero image uploaded", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "status_changed", description: "Status changed to Staged", user: "Admin", timestamp: "2026-03-23T10:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Hotelbeds", user: "System", timestamp: "2026-03-18T12:00:00Z" },
    ],
    createdAt: "2026-03-18T12:00:00Z",
    updatedAt: "2026-03-23T10:00:00Z",
  },
  {
    id: "prod-004",
    name: "Pierchic Restaurant",
    destination: "Dubai",
    category: "restaurants",
    status: "published",
    completeness: 82,
    heroImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
    tags: [
      { dimension: "budget_tier", value: "Luxury" },
      { dimension: "travel_theme", value: "Fine Dining" },
      { dimension: "audience", value: "Couples" },
    ],
    bookingSource: null,
    publishFlag: true,
    attributes: {
      location: { address: "Al Qasr Hotel, Madinat Jumeirah", city: "Dubai", country: "UAE", latitude: 25.1357, longitude: 55.1850 },
      pricing: { currency: "AED", amount: 450, per: "person" },
      starRating: null,
      duration: "2-3 hours",
      operatingHours: "12:30 PM - 11:30 PM",
      contactPhone: "+971 4 432 3232",
      contactEmail: null,
      website: "https://www.jumeirah.com/pierchic",
    },
    content: {
      shortDesc: "Award-winning seafood restaurant set on a private pier with stunning Arabian Gulf views.",
      longDesc: "Pierchic is Dubai's most iconic seafood restaurant, located at the end of a private pier at Madinat Jumeirah. Offering contemporary seafood cuisine with the freshest ingredients, guests enjoy uninterrupted views of the Arabian Gulf and Burj Al Arab.",
      metaTitle: "Pierchic Dubai | Fine Dining Seafood Restaurant at Madinat Jumeirah",
      metaDescription: "Dine at Pierchic, Dubai's premier seafood restaurant on a pier with stunning Gulf views. Book your table today.",
      faq: [
        { question: "Is there a dress code?", answer: "Smart casual attire is required. No beachwear or sportswear." },
      ],
      schemaMarkup: '{"@type":"Restaurant","name":"Pierchic","servesCuisine":"Seafood"}',
    },
    media: {
      images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-21T15:00:00Z" },
      { id: "h-2", action: "created", description: "Manually added", user: "Sarah M.", timestamp: "2026-03-19T10:00:00Z" },
    ],
    createdAt: "2026-03-19T10:00:00Z",
    updatedAt: "2026-03-21T15:00:00Z",
  },
  {
    id: "prod-005",
    name: "Emirates Palace Mandarin Oriental",
    destination: "Abu Dhabi",
    category: "hotels",
    status: "published",
    completeness: 91,
    heroImage: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600",
    tags: [
      { dimension: "budget_tier", value: "Ultra Luxury" },
      { dimension: "travel_theme", value: "Beach & Resort" },
      { dimension: "audience", value: "Couples" },
      { dimension: "season", value: "Year-round" },
    ],
    bookingSource: { id: "booking", name: "Booking.com", url: "https://booking.com/hotel/ae/emirates-palace" },
    publishFlag: true,
    attributes: {
      location: { address: "West Corniche Road", city: "Abu Dhabi", country: "UAE", latitude: 24.4615, longitude: 54.3175 },
      pricing: { currency: "AED", amount: 2400, per: "night" },
      starRating: 5,
      duration: null,
      operatingHours: "24/7",
      contactPhone: "+971 2 690 8888",
      contactEmail: "reservations@mandarinoriental.com",
      website: "https://www.mandarinoriental.com/abu-dhabi/emirates-palace",
    },
    content: {
      shortDesc: "Ultra-luxury palace hotel on Abu Dhabi's Corniche with 1.3km private beach and world-class spa.",
      longDesc: "Emirates Palace Mandarin Oriental is an iconic landmark in Abu Dhabi, offering unmatched luxury with 394 suites, a 1.3km private beach, two swimming pools, and a world-class spa. The hotel features gold-leaf interiors, 12 dining venues, and is set on 100 hectares of gardens.",
      metaTitle: "Emirates Palace Abu Dhabi | Ultra Luxury Hotel on the Corniche",
      metaDescription: "Stay at the iconic Emirates Palace in Abu Dhabi. 5-star luxury, private beach, world-class dining, and spa.",
      faq: [],
      schemaMarkup: '{"@type":"Hotel","name":"Emirates Palace Mandarin Oriental","starRating":{"ratingValue":"5"}}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600",
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "SEO check", status: "pass", details: "Score: 90/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-22T12:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Booking.com", user: "System", timestamp: "2026-03-18T09:00:00Z" },
    ],
    createdAt: "2026-03-18T09:00:00Z",
    updatedAt: "2026-03-22T12:00:00Z",
  },
  {
    id: "prod-006",
    name: "Desert Safari with BBQ Dinner",
    destination: "Dubai",
    category: "attractions",
    status: "draft",
    completeness: 45,
    heroImage: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=600",
    tags: [
      { dimension: "budget_tier", value: "Budget" },
      { dimension: "travel_theme", value: "Adventure" },
      { dimension: "audience", value: "Families" },
    ],
    bookingSource: { id: "gyg", name: "GetYourGuide", url: "https://getyourguide.com/dubai/desert-safari" },
    publishFlag: false,
    attributes: {
      location: { address: "Dubai Desert Conservation Reserve", city: "Dubai", country: "UAE", latitude: 24.8700, longitude: 55.6500 },
      pricing: { currency: "AED", amount: 149, per: "person" },
      starRating: null,
      duration: "6 hours",
      operatingHours: "3:00 PM - 9:00 PM",
      contactPhone: null,
      contactEmail: "tours@raynatours.com",
      website: null,
    },
    content: {
      shortDesc: "Thrilling dune bashing followed by a traditional BBQ dinner under the stars.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Missing long description, meta title, meta description", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Ingested from GetYourGuide", user: "System", timestamp: "2026-03-22T06:00:00Z" },
    ],
    createdAt: "2026-03-22T06:00:00Z",
    updatedAt: "2026-03-22T06:00:00Z",
  },
  {
    id: "prod-007",
    name: "Louvre Abu Dhabi",
    destination: "Abu Dhabi",
    category: "attractions",
    status: "published",
    completeness: 97,
    heroImage: "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Culture & Heritage" },
      { dimension: "audience", value: "Families" },
      { dimension: "audience", value: "Solo Travelers" },
      { dimension: "accessibility", value: "Wheelchair Accessible" },
    ],
    bookingSource: { id: "viator", name: "Viator", url: "https://viator.com/tours/Abu-Dhabi/Louvre" },
    publishFlag: true,
    attributes: {
      location: { address: "Saadiyat Island", city: "Abu Dhabi", country: "UAE", latitude: 24.5337, longitude: 54.3983 },
      pricing: { currency: "AED", amount: 63, per: "person" },
      starRating: null,
      duration: "2-3 hours",
      operatingHours: "10:00 AM - 6:30 PM (Closed Mondays)",
      contactPhone: "+971 600 565 566",
      contactEmail: null,
      website: "https://www.louvreabudhabi.ae",
    },
    content: {
      shortDesc: "The first universal museum in the Arab world, featuring art from around the globe under a stunning dome.",
      longDesc: "Louvre Abu Dhabi is a cultural landmark on Saadiyat Island, designed by Jean Nouvel. The museum houses a collection spanning from prehistory to the contemporary era, displayed beneath its iconic 180-meter dome that creates a mesmerizing 'rain of light' effect.",
      metaTitle: "Louvre Abu Dhabi Tickets | Art Museum on Saadiyat Island",
      metaDescription: "Visit Louvre Abu Dhabi, the first universal museum in the Arab world. Book tickets for an unforgettable cultural experience.",
      faq: [
        { question: "What are the opening hours?", answer: "Open daily 10 AM - 6:30 PM except Mondays. Late nights on Thursdays until 10 PM." },
        { question: "Is photography allowed?", answer: "Photography for personal use is permitted in permanent galleries. Flash photography is not allowed." },
      ],
      schemaMarkup: '{"@type":"Museum","name":"Louvre Abu Dhabi"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=600",
        "https://images.unsplash.com/photo-1564769625905-50e93615e769?w=600",
        "https://images.unsplash.com/photo-1580698484571-b7fd78797f48?w=600",
      ],
      videos: ["https://www.youtube.com/watch?v=example2"],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "SEO check", status: "pass", details: "Score: 95/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-20T14:00:00Z" },
      { id: "h-2", action: "content_generated", description: "Content generated successfully", user: "System", timestamp: "2026-03-19T08:00:00Z" },
      { id: "h-3", action: "created", description: "Ingested from Viator", user: "System", timestamp: "2026-03-17T10:00:00Z" },
    ],
    createdAt: "2026-03-17T10:00:00Z",
    updatedAt: "2026-03-20T14:00:00Z",
  },
  {
    id: "prod-008",
    name: "Abu Dhabi City Tour – Full Day",
    destination: "Abu Dhabi",
    category: "attractions",
    status: "staged",
    completeness: 68,
    heroImage: "https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=600",
    tags: [
      { dimension: "budget_tier", value: "Budget" },
      { dimension: "travel_theme", value: "Sightseeing" },
      { dimension: "audience", value: "Families" },
    ],
    bookingSource: { id: "klook", name: "Klook", url: "https://klook.com/activity/abu-dhabi-city-tour" },
    publishFlag: false,
    attributes: {
      location: { address: "Multiple locations", city: "Abu Dhabi", country: "UAE", latitude: 24.4539, longitude: 54.3773 },
      pricing: { currency: "AED", amount: 199, per: "person" },
      starRating: null,
      duration: "8 hours",
      operatingHours: "8:00 AM - 4:00 PM",
      contactPhone: null,
      contactEmail: "tours@raynatours.com",
      website: null,
    },
    content: {
      shortDesc: "Full-day guided tour covering Abu Dhabi's top landmarks including Sheikh Zayed Grand Mosque.",
      longDesc: "Explore the capital of the UAE on this comprehensive full-day city tour. Visit the magnificent Sheikh Zayed Grand Mosque, the Heritage Village, the Corniche, and more. Includes hotel pick-up and drop-off.",
      metaTitle: "Abu Dhabi Full Day City Tour | Top Landmarks",
      metaDescription: "Book an Abu Dhabi city tour. Visit Sheikh Zayed Mosque, Heritage Village, and more with hotel transfers.",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "warning", details: "Missing FAQ and schema markup", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "status_changed", description: "Moved to staging", user: "Admin", timestamp: "2026-03-23T09:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Klook", user: "System", timestamp: "2026-03-20T11:00:00Z" },
    ],
    createdAt: "2026-03-20T11:00:00Z",
    updatedAt: "2026-03-23T09:00:00Z",
  },
  {
    id: "prod-009",
    name: "Muscat Grand Hyatt",
    destination: "Muscat",
    category: "hotels",
    status: "draft",
    completeness: 35,
    heroImage: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600",
    tags: [
      { dimension: "budget_tier", value: "Luxury" },
      { dimension: "travel_theme", value: "Beach & Resort" },
    ],
    bookingSource: null,
    publishFlag: false,
    attributes: {
      location: { address: "Shatti Al Qurum", city: "Muscat", country: "Oman", latitude: 23.5980, longitude: 58.4060 },
      pricing: { currency: "OMR", amount: 95, per: "night" },
      starRating: 5,
      duration: null,
      operatingHours: "24/7",
      contactPhone: "+968 2464 1234",
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "5-star beachfront hotel in the heart of Muscat's diplomatic district.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Many required fields empty", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Ingested from Booking.com", user: "System", timestamp: "2026-03-23T07:00:00Z" },
    ],
    createdAt: "2026-03-23T07:00:00Z",
    updatedAt: "2026-03-23T07:00:00Z",
  },
  {
    id: "prod-010",
    name: "Dubai Marina Yacht Tour",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 85,
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Adventure" },
      { dimension: "audience", value: "Couples" },
      { dimension: "audience", value: "Groups" },
      { dimension: "season", value: "Oct-Apr" },
    ],
    bookingSource: { id: "viator", name: "Viator", url: "https://viator.com/tours/Dubai/Marina-Yacht-Tour" },
    publishFlag: true,
    attributes: {
      location: { address: "Dubai Marina Walk", city: "Dubai", country: "UAE", latitude: 25.0767, longitude: 55.1388 },
      pricing: { currency: "AED", amount: 350, per: "person" },
      starRating: null,
      duration: "2 hours",
      operatingHours: "9:00 AM - 8:00 PM",
      contactPhone: null,
      contactEmail: "yachts@raynatours.com",
      website: null,
    },
    content: {
      shortDesc: "Luxury yacht cruise through Dubai Marina with views of Ain Dubai, JBR, and Palm Jumeirah.",
      longDesc: "Set sail on a premium yacht tour through the stunning Dubai Marina. Enjoy panoramic views of the city's most iconic landmarks including Ain Dubai, the JBR skyline, Bluewaters Island, and Palm Jumeirah. Refreshments and snacks included.",
      metaTitle: "Dubai Marina Yacht Tour | Luxury Cruise Experience",
      metaDescription: "Book a luxury yacht tour in Dubai Marina. See Ain Dubai, JBR, and Palm Jumeirah. Refreshments included.",
      faq: [
        { question: "What is included?", answer: "Soft drinks, water, snacks, and a welcome drink are complimentary." },
      ],
      schemaMarkup: '{"@type":"TouristAttraction","name":"Dubai Marina Yacht Tour"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
        "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "SEO Score", description: "SEO check", status: "pass", details: "Score: 84/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-21T11:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Viator", user: "System", timestamp: "2026-03-18T14:00:00Z" },
    ],
    createdAt: "2026-03-18T14:00:00Z",
    updatedAt: "2026-03-21T11:00:00Z",
  },
  {
    id: "prod-011",
    name: "JW Marriott Marquis Dubai",
    destination: "Dubai",
    category: "hotels",
    status: "archived",
    completeness: 60,
    heroImage: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Business" },
      { dimension: "audience", value: "Business" },
    ],
    bookingSource: { id: "booking", name: "Booking.com", url: "https://booking.com/hotel/ae/jw-marriott-marquis" },
    publishFlag: false,
    attributes: {
      location: { address: "Sheikh Zayed Road, Business Bay", city: "Dubai", country: "UAE", latitude: 25.1870, longitude: 55.2638 },
      pricing: { currency: "AED", amount: 680, per: "night" },
      starRating: 5,
      duration: null,
      operatingHours: "24/7",
      contactPhone: "+971 4 414 0000",
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "World's tallest 5-star twin-tower hotel in the heart of Business Bay.",
      longDesc: "The JW Marriott Marquis Dubai stands as the world's tallest hotel, featuring twin towers that soar above Business Bay. With over 1,600 rooms and suites, 14 dining venues, and a rooftop infinity pool, it caters to both business and leisure travelers.",
      metaTitle: "JW Marriott Marquis Dubai | 5-Star Business Bay Hotel",
      metaDescription: "Stay at JW Marriott Marquis, the world's tallest hotel. Located in Business Bay with 14 restaurants and rooftop pool.",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "warning", details: "Missing FAQ and schema markup", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "archived", description: "Archived due to contract change", user: "Admin", timestamp: "2026-03-24T08:00:00Z" },
      { id: "h-2", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-15T12:00:00Z" },
      { id: "h-3", action: "created", description: "Ingested from Booking.com", user: "System", timestamp: "2026-03-10T09:00:00Z" },
    ],
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-24T08:00:00Z",
  },
  {
    id: "prod-012",
    name: "Muscat Airport Transfer – Shared Shuttle",
    destination: "Muscat",
    category: "transfers",
    status: "draft",
    completeness: 28,
    heroImage: null,
    tags: [
      { dimension: "budget_tier", value: "Budget" },
      { dimension: "travel_theme", value: "Transport" },
    ],
    bookingSource: null,
    publishFlag: false,
    attributes: {
      location: { address: "Muscat International Airport (MCT)", city: "Muscat", country: "Oman", latitude: 23.5933, longitude: 58.2844 },
      pricing: { currency: "OMR", amount: 8, per: "person" },
      starRating: null,
      duration: "45-90 minutes",
      operatingHours: "24/7",
      contactPhone: null,
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "Shared shuttle transfer from Muscat Airport to city hotels.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: { images: [], videos: [] },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Most content fields empty", checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "fail", details: "No hero image", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Manually created", user: "Sarah M.", timestamp: "2026-03-24T07:00:00Z" },
    ],
    createdAt: "2026-03-24T07:00:00Z",
    updatedAt: "2026-03-24T07:00:00Z",
  },
  {
    id: "prod-013",
    name: "Dubai Frame",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 92,
    heroImage: "https://images.unsplash.com/photo-1597659840241-37e2b4c2f990?w=600",
    tags: [
      { dimension: "budget_tier", value: "Budget" },
      { dimension: "travel_theme", value: "Sightseeing" },
      { dimension: "audience", value: "Families" },
      { dimension: "audience", value: "Solo Travelers" },
      { dimension: "accessibility", value: "Wheelchair Accessible" },
    ],
    bookingSource: { id: "gyg", name: "GetYourGuide", url: "https://getyourguide.com/dubai/dubai-frame" },
    publishFlag: true,
    attributes: {
      location: { address: "Zabeel Park, Gate 4", city: "Dubai", country: "UAE", latitude: 25.2350, longitude: 55.3000 },
      pricing: { currency: "AED", amount: 50, per: "person" },
      starRating: null,
      duration: "1 hour",
      operatingHours: "9:00 AM - 9:00 PM",
      contactPhone: "+971 800 3722",
      contactEmail: null,
      website: "https://www.dubaiframe.ae",
    },
    content: {
      shortDesc: "150-meter tall picture frame offering stunning views of both old and new Dubai.",
      longDesc: "Dubai Frame is an iconic landmark standing 150 meters tall in Zabeel Park. The attraction offers a unique perspective of the city, with views of old Dubai on one side and the gleaming skyline of new Dubai on the other. Features a glass-bottom walkway at the top.",
      metaTitle: "Dubai Frame Tickets | Iconic Landmark & Observation Deck",
      metaDescription: "Visit the Dubai Frame, a 150m tall landmark with panoramic city views. Book tickets online for the best prices.",
      faq: [
        { question: "Is there a glass floor?", answer: "Yes, the Sky Deck at the top features a thrilling glass-bottom walkway." },
        { question: "How long is the visit?", answer: "A typical visit takes about 1 hour, including the museum experience on the ground floor." },
      ],
      schemaMarkup: '{"@type":"TouristAttraction","name":"Dubai Frame"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1597659840241-37e2b4c2f990?w=600",
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "SEO check", status: "pass", details: "Score: 91/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-19T16:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from GetYourGuide", user: "System", timestamp: "2026-03-16T10:00:00Z" },
    ],
    createdAt: "2026-03-16T10:00:00Z",
    updatedAt: "2026-03-19T16:00:00Z",
  },
  {
    id: "prod-014",
    name: "The Kempinski Hotel Muscat",
    destination: "Muscat",
    category: "hotels",
    status: "staged",
    completeness: 75,
    heroImage: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600",
    tags: [
      { dimension: "budget_tier", value: "Luxury" },
      { dimension: "travel_theme", value: "Beach & Resort" },
      { dimension: "audience", value: "Couples" },
      { dimension: "season", value: "Oct-Apr" },
    ],
    bookingSource: { id: "agoda", name: "Agoda", url: "https://agoda.com/kempinski-muscat" },
    publishFlag: false,
    attributes: {
      location: { address: "Ghubrah Beach", city: "Muscat", country: "Oman", latitude: 23.6100, longitude: 58.3900 },
      pricing: { currency: "OMR", amount: 120, per: "night" },
      starRating: 5,
      duration: null,
      operatingHours: "24/7",
      contactPhone: "+968 2452 0200",
      contactEmail: "reservations@kempinski-muscat.com",
      website: "https://www.kempinski.com/muscat",
    },
    content: {
      shortDesc: "5-star beachfront resort in Muscat with a private beach, spa, and multiple dining venues.",
      longDesc: "The Kempinski Hotel Muscat offers a luxurious retreat on the shores of the Gulf of Oman. Featuring elegantly appointed rooms, a pristine private beach, state-of-the-art fitness center, and a variety of international dining options.",
      metaTitle: "Kempinski Hotel Muscat | 5-Star Beachfront Resort",
      metaDescription: "Book the Kempinski Hotel Muscat. Luxury beachfront resort with private beach, spa, and fine dining in Oman.",
      faq: [],
      schemaMarkup: '{"@type":"Hotel","name":"The Kempinski Hotel Muscat","starRating":{"ratingValue":"5"}}',
    },
    media: {
      images: ["https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "warning", details: "Missing FAQ", checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "status_changed", description: "Moved to staging", user: "Admin", timestamp: "2026-03-23T14:00:00Z" },
      { id: "h-2", action: "booking_source_assigned", description: "Agoda assigned as booking source", user: "Sarah M.", timestamp: "2026-03-22T10:00:00Z" },
      { id: "h-3", action: "created", description: "Ingested from Booking.com", user: "System", timestamp: "2026-03-19T08:00:00Z" },
    ],
    createdAt: "2026-03-19T08:00:00Z",
    updatedAt: "2026-03-23T14:00:00Z",
  },
  {
    id: "prod-015",
    name: "Al Mahara Restaurant",
    destination: "Dubai",
    category: "restaurants",
    status: "draft",
    completeness: 50,
    heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600",
    tags: [
      { dimension: "budget_tier", value: "Ultra Luxury" },
      { dimension: "travel_theme", value: "Fine Dining" },
      { dimension: "audience", value: "Couples" },
    ],
    bookingSource: null,
    publishFlag: false,
    attributes: {
      location: { address: "Burj Al Arab, Umm Suqeim", city: "Dubai", country: "UAE", latitude: 25.1412, longitude: 55.1852 },
      pricing: { currency: "AED", amount: 900, per: "person" },
      starRating: null,
      duration: "2-3 hours",
      operatingHours: "12:30 PM - 3:00 PM, 7:00 PM - 11:30 PM",
      contactPhone: "+971 4 301 7600",
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "Fine dining seafood restaurant inside the Burj Al Arab with a floor-to-ceiling aquarium.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Missing long description, meta, FAQ, schema", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Manually added", user: "Sarah M.", timestamp: "2026-03-23T16:00:00Z" },
    ],
    createdAt: "2026-03-23T16:00:00Z",
    updatedAt: "2026-03-23T16:00:00Z",
  },
  {
    id: "prod-016",
    name: "Abu Dhabi to Dubai Intercity Transfer",
    destination: "Abu Dhabi",
    category: "transfers",
    status: "published",
    completeness: 80,
    heroImage: null,
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Transport" },
      { dimension: "audience", value: "Business" },
      { dimension: "audience", value: "Families" },
    ],
    bookingSource: { id: "hotelbeds", name: "Hotelbeds", url: "https://hotelbeds.com/transfers/auh-to-dxb" },
    publishFlag: true,
    attributes: {
      location: { address: "Abu Dhabi Hotels", city: "Abu Dhabi", country: "UAE", latitude: 24.4539, longitude: 54.3773 },
      pricing: { currency: "AED", amount: 380, per: "vehicle" },
      starRating: null,
      duration: "1.5-2 hours",
      operatingHours: "24/7",
      contactPhone: null,
      contactEmail: "transfers@raynatours.com",
      website: null,
    },
    content: {
      shortDesc: "Private intercity transfer between Abu Dhabi and Dubai in a luxury sedan.",
      longDesc: "Enjoy a smooth, comfortable private transfer between Abu Dhabi and Dubai. Our professional drivers offer door-to-door service with luxury sedans, complimentary water, and WiFi. Perfect for business travelers and families.",
      metaTitle: "Abu Dhabi to Dubai Transfer | Private Sedan Service",
      metaDescription: "Book a private transfer from Abu Dhabi to Dubai. Luxury sedan, professional driver, door-to-door service.",
      faq: [
        { question: "How long is the drive?", answer: "The journey typically takes 1.5 to 2 hours depending on traffic conditions." },
      ],
      schemaMarkup: "",
    },
    media: { images: [], videos: [] },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "fail", details: "No hero image", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published despite missing image", user: "Admin", timestamp: "2026-03-22T09:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from Hotelbeds", user: "System", timestamp: "2026-03-17T13:00:00Z" },
    ],
    createdAt: "2026-03-17T13:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "prod-017",
    name: "Bait Al Luban Restaurant",
    destination: "Muscat",
    category: "restaurants",
    status: "draft",
    completeness: 40,
    heroImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Culture & Heritage" },
      { dimension: "audience", value: "Families" },
    ],
    bookingSource: null,
    publishFlag: false,
    attributes: {
      location: { address: "Muttrah Corniche", city: "Muscat", country: "Oman", latitude: 23.6195, longitude: 58.5641 },
      pricing: { currency: "OMR", amount: 15, per: "person" },
      starRating: null,
      duration: "1-2 hours",
      operatingHours: "9:00 AM - 11:00 PM",
      contactPhone: "+968 2471 4842",
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "Traditional Omani restaurant on the Muttrah Corniche with views of the harbour.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Many content fields empty", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Manually added", user: "Sarah M.", timestamp: "2026-03-24T10:00:00Z" },
    ],
    createdAt: "2026-03-24T10:00:00Z",
    updatedAt: "2026-03-24T10:00:00Z",
  },
  {
    id: "prod-018",
    name: "IMG Worlds of Adventure",
    destination: "Dubai",
    category: "attractions",
    status: "staged",
    completeness: 78,
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Theme Parks" },
      { dimension: "audience", value: "Families" },
      { dimension: "audience", value: "Groups" },
      { dimension: "accessibility", value: "Wheelchair Accessible" },
    ],
    bookingSource: { id: "klook", name: "Klook", url: "https://klook.com/activity/img-worlds-of-adventure" },
    publishFlag: false,
    attributes: {
      location: { address: "E311, Sheikh Mohammed Bin Zayed Rd", city: "Dubai", country: "UAE", latitude: 25.0477, longitude: 55.2302 },
      pricing: { currency: "AED", amount: 299, per: "person" },
      starRating: null,
      duration: "4-6 hours",
      operatingHours: "11:00 AM - 9:00 PM",
      contactPhone: "+971 4 403 8888",
      contactEmail: null,
      website: "https://www.imgworlds.com",
    },
    content: {
      shortDesc: "World's largest indoor theme park featuring Marvel, Cartoon Network, and Lost Valley zones.",
      longDesc: "IMG Worlds of Adventure is the world's largest indoor theme and amusement park. Spanning 1.5 million square feet, the park features four epic zones: Marvel, Cartoon Network, Lost Valley – Dinosaur Adventure, and IMG Boulevard. With over 20 rides, attractions for all ages.",
      metaTitle: "IMG Worlds of Adventure Dubai | Indoor Theme Park Tickets",
      metaDescription: "Visit IMG Worlds of Adventure, the world's largest indoor theme park in Dubai. Marvel, Cartoon Network zones & more.",
      faq: [
        { question: "Is it suitable for young children?", answer: "Yes, the park has attractions suitable for all ages, including gentle rides in the Cartoon Network zone." },
      ],
      schemaMarkup: '{"@type":"AmusementPark","name":"IMG Worlds of Adventure"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600",
        "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "status_changed", description: "Moved to staging", user: "Admin", timestamp: "2026-03-24T11:00:00Z" },
      { id: "h-2", action: "content_generated", description: "Content generated successfully", user: "System", timestamp: "2026-03-23T08:00:00Z" },
      { id: "h-3", action: "created", description: "Ingested from Klook", user: "System", timestamp: "2026-03-20T09:00:00Z" },
    ],
    createdAt: "2026-03-20T09:00:00Z",
    updatedAt: "2026-03-24T11:00:00Z",
  },
  {
    id: "prod-019",
    name: "Royal Mutrah Fort Tour",
    destination: "Muscat",
    category: "attractions",
    status: "draft",
    completeness: 30,
    heroImage: "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=600",
    tags: [
      { dimension: "budget_tier", value: "Budget" },
      { dimension: "travel_theme", value: "Culture & Heritage" },
    ],
    bookingSource: null,
    publishFlag: false,
    attributes: {
      location: { address: "Muttrah, Muscat", city: "Muscat", country: "Oman", latitude: 23.6200, longitude: 58.5700 },
      pricing: { currency: "OMR", amount: 5, per: "person" },
      starRating: null,
      duration: "1 hour",
      operatingHours: "8:00 AM - 5:00 PM",
      contactPhone: null,
      contactEmail: null,
      website: null,
    },
    content: {
      shortDesc: "Historic Portuguese-era fort overlooking the Muttrah harbour.",
      longDesc: "",
      metaTitle: "",
      metaDescription: "",
      faq: [],
      schemaMarkup: "",
    },
    media: {
      images: ["https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=600"],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "fail", details: "Many fields empty", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "created", description: "Manually added", user: "Sarah M.", timestamp: "2026-03-24T12:00:00Z" },
    ],
    createdAt: "2026-03-24T12:00:00Z",
    updatedAt: "2026-03-24T12:00:00Z",
  },
  {
    id: "prod-020",
    name: "Dubai Mall Aquarium & Underwater Zoo",
    destination: "Dubai",
    category: "attractions",
    status: "published",
    completeness: 90,
    heroImage: "https://images.unsplash.com/photo-1559825481-12a05cc00344?w=600",
    tags: [
      { dimension: "budget_tier", value: "Mid-range" },
      { dimension: "travel_theme", value: "Adventure" },
      { dimension: "audience", value: "Families" },
      { dimension: "accessibility", value: "Wheelchair Accessible" },
    ],
    bookingSource: { id: "gyg", name: "GetYourGuide", url: "https://getyourguide.com/dubai/aquarium" },
    publishFlag: true,
    attributes: {
      location: { address: "The Dubai Mall, Financial Center Rd", city: "Dubai", country: "UAE", latitude: 25.1978, longitude: 55.2795 },
      pricing: { currency: "AED", amount: 120, per: "person" },
      starRating: null,
      duration: "1.5-2 hours",
      operatingHours: "10:00 AM - 12:00 AM",
      contactPhone: "+971 4 448 5200",
      contactEmail: null,
      website: "https://www.thedubaiaquarium.com",
    },
    content: {
      shortDesc: "One of the world's largest suspended aquariums with 33,000+ aquatic animals and an underwater zoo.",
      longDesc: "The Dubai Mall Aquarium and Underwater Zoo is home to over 33,000 aquatic animals, including sharks, rays, and an enormous King Croc. Walk through the 48-meter tunnel for an immersive underwater experience, or take a glass-bottom boat ride across the top of the tank.",
      metaTitle: "Dubai Aquarium & Underwater Zoo | Dubai Mall Attraction",
      metaDescription: "Visit Dubai Aquarium in The Dubai Mall. 33,000+ aquatic animals, underwater tunnel, glass-bottom boats. Book tickets.",
      faq: [
        { question: "Can I see the aquarium for free?", answer: "The main tank is visible for free from the mall. Paid tickets give access to the tunnel, zoo, and special experiences." },
      ],
      schemaMarkup: '{"@type":"Aquarium","name":"Dubai Mall Aquarium & Underwater Zoo"}',
    },
    media: {
      images: [
        "https://images.unsplash.com/photo-1559825481-12a05cc00344?w=600",
        "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=600",
      ],
      videos: [],
    },
    qualityChecks: [
      { id: "qc-1", name: "Content Completeness", description: "Required fields check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-2", name: "Image Quality", description: "Hero image check", status: "pass", details: null, checkedAt: "2026-03-24T10:00:00Z" },
      { id: "qc-3", name: "SEO Score", description: "SEO check", status: "pass", details: "Score: 89/100", checkedAt: "2026-03-24T10:00:00Z" },
    ],
    history: [
      { id: "h-1", action: "published", description: "Published to catalog", user: "Admin", timestamp: "2026-03-20T10:00:00Z" },
      { id: "h-2", action: "created", description: "Ingested from GetYourGuide", user: "System", timestamp: "2026-03-17T08:00:00Z" },
    ],
    createdAt: "2026-03-17T08:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
];
