import type {
  Destination,
  IntelligenceSummary,
} from "@/types/destinations";

export const MOCK_DESTINATIONS: Destination[] = [
  {
    id: "dest-001",
    name: "Dubai",
    country: "United Arab Emirates",
    countryFlag: "\u{1F1E6}\u{1F1EA}",
    region: "Middle East",
    city: "Dubai",
    timezone: "Asia/Dubai",
    latitude: 25.2048,
    longitude: 55.2708,
    status: "active",
    productCounts: { hotels: 342, attractions: 518, transfers: 89, restaurants: 156 },
    lastIngestionRun: {
      date: "2026-03-24T14:30:00Z",
      status: "completed",
      recordsProcessed: 1243,
      durationMs: 342000,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-22T10:00:00Z",
      keywordsFound: 847,
      sourcesApproved: 12,
    },
  },
  {
    id: "dest-002",
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    countryFlag: "\u{1F1E6}\u{1F1EA}",
    region: "Middle East",
    city: "Abu Dhabi",
    timezone: "Asia/Dubai",
    latitude: 24.4539,
    longitude: 54.3773,
    status: "active",
    productCounts: { hotels: 198, attractions: 234, transfers: 56, restaurants: 87 },
    lastIngestionRun: {
      date: "2026-03-25T09:15:00Z",
      status: "running",
      recordsProcessed: 567,
      durationMs: 0,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-20T08:00:00Z",
      keywordsFound: 412,
      sourcesApproved: 8,
    },
  },
  {
    id: "dest-003",
    name: "Muscat",
    country: "Oman",
    countryFlag: "\u{1F1F4}\u{1F1F2}",
    region: "Middle East",
    city: "Muscat",
    timezone: "Asia/Muscat",
    latitude: 23.588,
    longitude: 58.3829,
    status: "active",
    productCounts: { hotels: 87, attractions: 134, transfers: 23, restaurants: 45 },
    lastIngestionRun: {
      date: "2026-03-23T07:00:00Z",
      status: "failed",
      recordsProcessed: 0,
      durationMs: 18000,
    },
    intelligenceFilter: {
      lastRunDate: null,
      keywordsFound: 0,
      sourcesApproved: 0,
    },
  },
  {
    id: "dest-004",
    name: "Tbilisi",
    country: "Georgia",
    countryFlag: "\u{1F1EC}\u{1F1EA}",
    region: "Caucasus",
    city: "Tbilisi",
    timezone: "Asia/Tbilisi",
    latitude: 41.7151,
    longitude: 44.8271,
    status: "active",
    productCounts: { hotels: 156, attractions: 189, transfers: 34, restaurants: 67 },
    lastIngestionRun: {
      date: "2026-03-24T22:00:00Z",
      status: "completed",
      recordsProcessed: 389,
      durationMs: 156000,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-18T12:00:00Z",
      keywordsFound: 234,
      sourcesApproved: 6,
    },
  },
  {
    id: "dest-005",
    name: "Male",
    country: "Maldives",
    countryFlag: "\u{1F1F2}\u{1F1FB}",
    region: "South Asia",
    city: "Male",
    timezone: "Indian/Maldives",
    latitude: 4.1755,
    longitude: 73.5093,
    status: "active",
    productCounts: { hotels: 234, attractions: 78, transfers: 45, restaurants: 34 },
    lastIngestionRun: {
      date: "2026-03-22T16:00:00Z",
      status: "completed",
      recordsProcessed: 198,
      durationMs: 89000,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-15T09:00:00Z",
      keywordsFound: 156,
      sourcesApproved: 5,
    },
  },
  {
    id: "dest-006",
    name: "Denpasar",
    country: "Indonesia",
    countryFlag: "\u{1F1EE}\u{1F1E9}",
    region: "Southeast Asia",
    city: "Bali",
    timezone: "Asia/Makassar",
    latitude: -8.65,
    longitude: 115.2167,
    status: "inactive",
    productCounts: { hotels: 45, attractions: 67, transfers: 12, restaurants: 23 },
    lastIngestionRun: null,
    intelligenceFilter: {
      lastRunDate: null,
      keywordsFound: 0,
      sourcesApproved: 0,
    },
  },
  {
    id: "dest-007",
    name: "Bangkok",
    country: "Thailand",
    countryFlag: "\u{1F1F9}\u{1F1ED}",
    region: "Southeast Asia",
    city: "Bangkok",
    timezone: "Asia/Bangkok",
    latitude: 13.7563,
    longitude: 100.5018,
    status: "active",
    productCounts: { hotels: 278, attractions: 345, transfers: 67, restaurants: 189 },
    lastIngestionRun: {
      date: "2026-03-24T06:00:00Z",
      status: "completed",
      recordsProcessed: 456,
      durationMs: 234000,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-21T14:00:00Z",
      keywordsFound: 523,
      sourcesApproved: 9,
    },
  },
  {
    id: "dest-008",
    name: "Istanbul",
    country: "Turkey",
    countryFlag: "\u{1F1F9}\u{1F1F7}",
    region: "Europe / Middle East",
    city: "Istanbul",
    timezone: "Europe/Istanbul",
    latitude: 41.0082,
    longitude: 28.9784,
    status: "active",
    productCounts: { hotels: 189, attractions: 267, transfers: 45, restaurants: 134 },
    lastIngestionRun: {
      date: "2026-03-23T18:00:00Z",
      status: "completed",
      recordsProcessed: 312,
      durationMs: 178000,
    },
    intelligenceFilter: {
      lastRunDate: "2026-03-19T11:00:00Z",
      keywordsFound: 389,
      sourcesApproved: 7,
    },
  },
];

export const MOCK_INTELLIGENCE_SUMMARIES: Record<string, IntelligenceSummary> = {
  "dest-001": {
    destinationId: "dest-001",
    topKeywords: [
      { id: "kw-1", keyword: "desert safari dubai", category: "attractions", volume: 74000, difficulty: 72, intent: "transactional" },
      { id: "kw-2", keyword: "dubai hotel deals", category: "hotels", volume: 49000, difficulty: 85, intent: "commercial" },
      { id: "kw-3", keyword: "burj khalifa tickets", category: "attractions", volume: 110000, difficulty: 68, intent: "transactional" },
      { id: "kw-4", keyword: "dubai airport transfer", category: "transfers", volume: 33000, difficulty: 45, intent: "transactional" },
      { id: "kw-5", keyword: "best restaurants dubai marina", category: "restaurants", volume: 18000, difficulty: 52, intent: "informational" },
      { id: "kw-6", keyword: "dubai frame tickets price", category: "attractions", volume: 27000, difficulty: 38, intent: "commercial" },
    ],
    approvedSources: [
      { id: "src-1", name: "Viator API", type: "api", categories: ["attractions", "transfers"], relevanceScore: 95, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 1 },
      { id: "src-2", name: "Booking.com", type: "aggregator", categories: ["hotels"], relevanceScore: 92, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 2 },
      { id: "src-3", name: "TripAdvisor", type: "review_platform", categories: ["restaurants", "attractions"], relevanceScore: 88, tosStatus: "pending_review", ingestionMethod: "scrape", priorityRank: 3 },
      { id: "src-4", name: "Dubai Tourism Board", type: "government", categories: ["attractions", "restaurants"], relevanceScore: 85, tosStatus: "compliant", ingestionMethod: "feed", priorityRank: 4 },
      { id: "src-5", name: "GetYourGuide", type: "aggregator", categories: ["attractions", "transfers"], relevanceScore: 90, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 5 },
    ],
  },
  "dest-002": {
    destinationId: "dest-002",
    topKeywords: [
      { id: "kw-7", keyword: "louvre abu dhabi tickets", category: "attractions", volume: 45000, difficulty: 55, intent: "transactional" },
      { id: "kw-8", keyword: "abu dhabi hotels near corniche", category: "hotels", volume: 22000, difficulty: 67, intent: "commercial" },
      { id: "kw-9", keyword: "ferrari world tickets", category: "attractions", volume: 38000, difficulty: 62, intent: "transactional" },
      { id: "kw-10", keyword: "abu dhabi to dubai transfer", category: "transfers", volume: 15000, difficulty: 35, intent: "transactional" },
    ],
    approvedSources: [
      { id: "src-6", name: "Viator API", type: "api", categories: ["attractions"], relevanceScore: 93, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 1 },
      { id: "src-7", name: "Abu Dhabi Culture", type: "government", categories: ["attractions"], relevanceScore: 87, tosStatus: "compliant", ingestionMethod: "feed", priorityRank: 2 },
      { id: "src-8", name: "Hotelbeds", type: "aggregator", categories: ["hotels", "transfers"], relevanceScore: 85, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 3 },
    ],
  },
  "dest-004": {
    destinationId: "dest-004",
    topKeywords: [
      { id: "kw-11", keyword: "tbilisi old town tours", category: "attractions", volume: 12000, difficulty: 32, intent: "transactional" },
      { id: "kw-12", keyword: "georgia wine tours", category: "attractions", volume: 18000, difficulty: 40, intent: "informational" },
      { id: "kw-13", keyword: "tbilisi boutique hotels", category: "hotels", volume: 8000, difficulty: 45, intent: "commercial" },
    ],
    approvedSources: [
      { id: "src-9", name: "GetYourGuide", type: "aggregator", categories: ["attractions"], relevanceScore: 88, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 1 },
      { id: "src-10", name: "Georgia Travel", type: "government", categories: ["attractions", "hotels"], relevanceScore: 80, tosStatus: "compliant", ingestionMethod: "feed", priorityRank: 2 },
    ],
  },
  "dest-007": {
    destinationId: "dest-007",
    topKeywords: [
      { id: "kw-14", keyword: "bangkok temples tour", category: "attractions", volume: 56000, difficulty: 58, intent: "transactional" },
      { id: "kw-15", keyword: "bangkok street food tour", category: "restaurants", volume: 34000, difficulty: 42, intent: "informational" },
      { id: "kw-16", keyword: "bangkok luxury hotels", category: "hotels", volume: 28000, difficulty: 75, intent: "commercial" },
      { id: "kw-17", keyword: "bangkok airport transfer", category: "transfers", volume: 41000, difficulty: 38, intent: "transactional" },
    ],
    approvedSources: [
      { id: "src-11", name: "Viator API", type: "api", categories: ["attractions", "transfers"], relevanceScore: 94, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 1 },
      { id: "src-12", name: "Agoda", type: "aggregator", categories: ["hotels"], relevanceScore: 91, tosStatus: "compliant", ingestionMethod: "api", priorityRank: 2 },
      { id: "src-13", name: "TAT Thailand", type: "government", categories: ["attractions", "restaurants"], relevanceScore: 82, tosStatus: "compliant", ingestionMethod: "feed", priorityRank: 3 },
      { id: "src-14", name: "Klook", type: "aggregator", categories: ["attractions", "transfers"], relevanceScore: 89, tosStatus: "pending_review", ingestionMethod: "api", priorityRank: 4 },
    ],
  },
};

export const COUNTRY_OPTIONS = [
  { value: "United Arab Emirates", label: "United Arab Emirates", flag: "\u{1F1E6}\u{1F1EA}" },
  { value: "Oman", label: "Oman", flag: "\u{1F1F4}\u{1F1F2}" },
  { value: "Georgia", label: "Georgia", flag: "\u{1F1EC}\u{1F1EA}" },
  { value: "Maldives", label: "Maldives", flag: "\u{1F1F2}\u{1F1FB}" },
  { value: "Indonesia", label: "Indonesia", flag: "\u{1F1EE}\u{1F1E9}" },
  { value: "Thailand", label: "Thailand", flag: "\u{1F1F9}\u{1F1ED}" },
  { value: "Turkey", label: "Turkey", flag: "\u{1F1F9}\u{1F1F7}" },
  { value: "India", label: "India", flag: "\u{1F1EE}\u{1F1F3}" },
  { value: "Egypt", label: "Egypt", flag: "\u{1F1EA}\u{1F1EC}" },
  { value: "Saudi Arabia", label: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}" },
  { value: "Singapore", label: "Singapore", flag: "\u{1F1F8}\u{1F1EC}" },
  { value: "Sri Lanka", label: "Sri Lanka", flag: "\u{1F1F1}\u{1F1F0}" },
];

export const COUNTRY_CITIES: Record<string, string[]> = {
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Al Ain"],
  "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  "Maldives": ["Male", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo"],
  "Indonesia": ["Jakarta", "Bali", "Surabaya", "Bandung", "Yogyakarta", "Medan", "Lombok"],
  "Thailand": ["Bangkok", "Phuket", "Chiang Mai", "Pattaya", "Krabi", "Koh Samui"],
  "Turkey": ["Istanbul", "Ankara", "Antalya", "Izmir", "Cappadocia", "Bodrum"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Goa", "Jaipur", "Chennai", "Kolkata", "Hyderabad", "Agra", "Udaipur"],
  "Egypt": ["Cairo", "Alexandria", "Luxor", "Aswan", "Hurghada", "Sharm El Sheikh"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Al Khobar"],
  "Singapore": ["Singapore"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Ella", "Negombo", "Sigiriya"],
};
